import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const read = (path: string) => readFileSync(join(process.cwd(), path), "utf8");

const rootRoute = read("src/routes/__root.tsx");
const versionRoute = read("src/routes/version[.]json.ts");
const provenanceLib = read("src/lib/build-provenance.ts");

// Patterns that must NEVER appear in the provenance exposure path.
const FORBIDDEN_PATTERNS = [
  /SERVICE_ROLE/i,
  /SUPABASE_SERVICE/i,
  /process\.env(?!\.\w*SHA)/i, // env reads other than *SHA candidates
  /JSON\.stringify\(process\.env/,
  /JWT/i,
  /PASSWORD/i,
  /SECRET/i,
  /\banon\b.*\bkey\b/i,
];

describe("meta tag exposure (src/routes/__root.tsx)", () => {
  test("exposes the build SHA via a build-sha meta tag", () => {
    expect(rootRoute).toContain('{ name: "build-sha", content: BUILD_SHA }');
  });

  test("sources the value from the single source-of-truth module", () => {
    expect(rootRoute).toContain('from "@/lib/build-provenance"');
  });

  test("meta tag content is the validated constant, not a raw env read", () => {
    expect(rootRoute).not.toMatch(/name: "build-sha", content: import\.meta\.env/);
    expect(rootRoute).not.toMatch(/name: "build-sha", content: process\.env/);
  });
});

describe("/version.json server route", () => {
  test("is registered with the TanStack server handler pattern", () => {
    expect(versionRoute).toContain('createFileRoute("/version.json")');
    expect(versionRoute).toContain("server: {");
    expect(versionRoute).toContain("GET: async () => {");
  });

  test("returns the same frozen payload as the meta tag", () => {
    expect(versionRoute).toContain("serializeBuildProvenance()");
    expect(versionRoute).toContain('from "@/lib/build-provenance"');
  });

  test("is never cached (service worker staleness protection)", () => {
    expect(versionRoute).toContain('"Cache-Control": "no-store"');
  });

  test("registers itself via the file-based route id (build-time route tree generation)", () => {
    // src/routeTree.gen.ts is regenerated by the TanStack Router plugin on
    // every dev/build run from the route FILES, so the presence of this file
    // with the correct createFileRoute id is what guarantees registration.
    // The committed generated file is intentionally left untouched (it is
    // overwritten by every build; hand-editing it adds risk, not value).
    expect(versionRoute).toContain('createFileRoute("/version.json")');
    expect(versionRoute).toContain("export const Route =");
  });
});

describe("source-of-truth module (src/lib/build-provenance.ts)", () => {
  test("validates with a 7-40 hex pattern and an unknown sentinel", () => {
    expect(provenanceLib).toContain("/^[0-9a-f]{7,40}$/");
    expect(provenanceLib).toContain('"unknown"');
  });

  test("reads only the build-time-injected define value", () => {
    expect(provenanceLib).toContain("import.meta.env.VITE_BUILD_SHA");
  });

  test("freezes the public shape to exactly { sha }", () => {
    expect(provenanceLib).toContain("return { sha: BUILD_SHA };");
  });
});

describe("no secret or environment leakage in the exposure path", () => {
  test("provenance lib, meta tag and version route contain no secret patterns", () => {
    for (const [name, source] of [
      ["src/lib/build-provenance.ts", provenanceLib],
      ["src/routes/version[.]json.ts", versionRoute],
    ] as const) {
      for (const pattern of FORBIDDEN_PATTERNS) {
        expect({ file: name, leaked: pattern.test(source) }).toEqual({
          file: name,
          leaked: false,
        });
      }
    }
  });

  test("__root.tsx only adds the validated constant (no new env reads)", () => {
    // The meta tag line must reference BUILD_SHA; the file must not read
    // process.env at all in the provenance path.
    expect(rootRoute).not.toContain("process.env");
  });
});
