#!/usr/bin/env bun
/**
 * PORTAL-B1-PR310 Definitive Operator Architecture — LONGRUN-14
 * Canonical B1 execution fixture generator.
 *
 * MIGRATION_REPLAY_EQUIVALENCE = NOT_CLAIMED
 *
 * Strategy (Phase B Option 3):
 *   - Repository migrations under supabase/migrations/ are never read,
 *     modified, or replayed by this generator.
 *   - The canonical execution fixture is the pinned local PG17 schema+data
 *     snapshot at:
 *       scripts/b1-rpc-principal-harness-01/local-operator-simulation/00-canonical-b1-schema.sql
 *   - That snapshot already contains the platform bootstrap, the full public
 *     schema, and Fixture-13 (19 requests / 104 runtime steps / 19 active).
 *   - This generator prepends a preamble, appends the small canonical-fixture
 *     prestate files in deterministic filename order, and writes the result to
 *     the gitignored generated output directory.
 *   - Function semantic equivalence to production is proved independently by
 *     tests that hash the 36 canonical functions and compare to
 *     scripts/b1-rpc-principal-harness-01/TARGET-MANIFEST.json.
 *
 * Output (gitignored):
 *   scripts/b1-definitive-operator-architecture-14/generated/canonical-b1-fixture.sql
 */

import { readFileSync, mkdirSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const outDir = join(root, "scripts/b1-definitive-operator-architecture-14/generated");
const fixtureDir = join(root, "scripts/b1-definitive-operator-architecture-14/canonical-fixture");
const schemaSnapshotPath = "scripts/b1-rpc-principal-harness-01/local-operator-simulation/00-canonical-b1-schema.sql";

const preamble = `-- ============================================================================
-- PORTAL-B1-PR310 Definitive Operator Architecture — LONGRUN-14
-- CANONICAL B1 EXECUTION FIXTURE (GENERATED)
--
-- MIGRATION_REPLAY_EQUIVALENCE = NOT_CLAIMED
--
-- This file is a local disposable-PG17 execution fixture. It is NOT a
-- byte-for-byte replay of production migrations and must not be used as
-- evidence of migration equivalence. Independent function-graph attestation
-- is provided by tests that compare the 36 canonical function hashes to
-- scripts/b1-rpc-principal-harness-01/TARGET-MANIFEST.json.
--
-- Source snapshot: ${schemaSnapshotPath}
-- Generated by: scripts/b1-definitive-operator-architecture-14/build-canonical-b1-fixture.ts
-- Do not edit by hand. This file is gitignored.
-- ============================================================================
\\set ON_ERROR_STOP on
`;

function main() {
  mkdirSync(outDir, { recursive: true });

  const snapshot = readFileSync(join(root, schemaSnapshotPath), "utf8");
  const parts: string[] = [preamble.trimEnd(), snapshot];

  const fixtureFiles = readdirSync(fixtureDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  for (const f of fixtureFiles) {
    parts.push(`\n-- ============================================================================\n-- canonical-fixture/${f}\n-- ============================================================================\n`);
    parts.push(readFileSync(join(fixtureDir, f), "utf8"));
  }

  const sql = parts.join("\n");
  const outPath = join(outDir, "canonical-b1-fixture.sql");
  writeFileSync(outPath, sql, "utf8");

  console.log(`Generated ${outPath} (${sql.length} bytes)`);
  console.log(`MIGRATION_REPLAY_EQUIVALENCE = NOT_CLAIMED`);
  console.log(`Source snapshot: ${schemaSnapshotPath}`);
  console.log(`Appended ${fixtureFiles.length} canonical-fixture files:`);
  for (const f of fixtureFiles) console.log(`  - ${f}`);
}

main();
