/**
 * The canonical portal reports catalog.
 *
 * Every entry is evidence-anchored to paths on `main` (see INVENTORY.md basis:
 * PORTAL-REPORTS-CANONICAL-CATALOG-AND-TRACEABILITY-01 inventory, head
 * 0e2d25c9; re-verified at branch time against 1cedb888). Status decisions
 * follow the strict rules documented in
 * docs/PORTAL-REPORTS-CANONICAL-CATALOG-AND-TRACEABILITY-01-REPORT.md:
 * LIVE requires source + permission + route + automated test + real wiring,
 * all proven by file paths. `tests/admin/` contains no report tests, so the
 * wired `/admin/reports` sections are DATA_DEPENDENT, not LIVE.
 */

import type { ReportEntry } from "./types";

export const REPORT_CATALOG_ENTRIES: readonly ReportEntry[] = [
  // ------------------------------------------------------------------
  // Wired admin report sections (source + guard + route + wiring; no tests)
  // ------------------------------------------------------------------
  {
    report_code: "ADM-STUDENTS-DIRECTORY",
    name_ar: "تقرير دليل الطلاب",
    description:
      "قائمة الطلاب مع ترشيحات (نظام الدراسة/قسم/برنامج/مستوى/سنة/فصل/حالة/حالة حساب) وترقيم صفحات، مع تصدير CSV/XLSX.",
    beneficiaries: ["dean", "operational_units_staff", "vp_student_affairs", "vp_academic_affairs"],
    required_role: ["admin", "system_admin", "dean", "registrar", "student_affairs"],
    data_scope: "university",
    source:
      "table: student_profiles (عبر supabaseAdmin) — getStudentsReportForAdmin في src/lib/admin-reports.functions.ts",
    filters: ["study_system", "department_id", "program_id", "level_id", "academic_year_id", "semester_id", "status", "account_status", "page", "pageSize"],
    sensitivity: "personal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: [],
    dependencies: ["src/lib/authz.server.ts:assertStudentRead", "src/lib/reports/export.ts"],
    status: "DATA_DEPENDENT",
    blocker: "لا اختبار مؤتمت مثبت للتقرير (tests/admin/ بلا اختبارات تقارير)",
    evidence: [
      "src/lib/admin-reports.functions.ts (getStudentsReportForAdmin)",
      "src/routes/admin/reports.tsx (قسم students — StudentsReport)",
      "tests/admin/ (لا اختبارات تقارير)",
    ],
  },
  {
    report_code: "ADM-IMPORT-JOBS",
    name_ar: "تقرير مهام الاستيراد وأخطاؤها",
    description: "متابعة مهام استيراد البيانات مع تفصيل أخطاء كل مهمة.",
    beneficiaries: ["operational_units_staff", "vp_academic_affairs", "dean"],
    required_role: ["admin", "system_admin", "registrar"],
    data_scope: "university",
    source:
      "جداول مهام الاستيراد — getImportJobsReportForAdmin / getImportJobErrorsForAdmin في src/lib/admin-reports.functions.ts (IMPORT_REPORT_ROLES)",
    filters: ["job_status", "job_type"],
    sensitivity: "internal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: [],
    dependencies: ["src/lib/imports/ (PR #193/#195)"],
    status: "DATA_DEPENDENT",
    blocker: "لا اختبار مؤتمت مثبت للتقرير",
    evidence: [
      "src/lib/admin-reports.functions.ts (getImportJobsReportForAdmin/getImportJobErrorsForAdmin)",
      "src/routes/admin/reports.tsx (قسم imports — ImportJobsReport)",
    ],
  },
  {
    report_code: "ADM-STUDENT-ACCOUNTS",
    name_ar: "تقرير حسابات الطلاب",
    description: "حالة حسابات الدخول للطلاب (من لديه حساب/بدون).",
    beneficiaries: ["operational_units_staff", "vp_student_affairs", "dean"],
    required_role: ["system_admin", "admin", "dean", "registrar", "finance_officer", "student_affairs"],
    data_scope: "university",
    source:
      "جدول student_profiles/حسابات — getStudentAccountsReportForAdmin في src/lib/admin-reports.functions.ts (REPORTS_ROLES)",
    filters: ["account_status", "department_id"],
    sensitivity: "personal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: [],
    dependencies: ["src/lib/authz.server.ts:assertReportsAccess"],
    status: "DATA_DEPENDENT",
    blocker: "لا اختبار مؤتمت مثبت",
    evidence: [
      "src/lib/admin-reports.functions.ts (getStudentAccountsReportForAdmin)",
      "src/routes/admin/reports.tsx (قسم accounts — StudentAccountsReport)",
    ],
  },
  {
    report_code: "ADM-ACADEMIC-STRUCTURE",
    name_ar: "التقارير الأكاديمية (برامج/خطط دراسية/مقررات/تغطية الخطط)",
    description: "أربعة تقارير فرعية عن الهيكل الأكاديمي وتغطية الخطط الدراسية ضمن قسم academic.",
    beneficiaries: ["vp_academic_affairs", "dean", "academic_affairs", "dept_head_coordinator"],
    required_role: ["system_admin", "admin", "dean", "registrar", "finance_officer", "student_affairs"],
    data_scope: "university",
    source:
      "جداول programs/study_plans/courses — getAcademicProgramsReportForAdmin + getStudyPlansReportForAdmin + getCoursesReportForAdmin + getStudyPlanCoverageReportForAdmin في src/lib/admin-reports.functions.ts",
    filters: ["department_id", "program_id"],
    sensitivity: "internal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: [],
    dependencies: ["src/lib/admin-reports.functions.ts:getAcademicReportLookupsForAdmin"],
    status: "DATA_DEPENDENT",
    blocker: "لا اختبار مؤتمت مثبت",
    evidence: [
      "src/lib/admin-reports.functions.ts (getAcademic*ReportForAdmin ×4)",
      "src/routes/admin/reports.tsx (قسم academic — AcademicReports)",
    ],
  },
  {
    report_code: "ADM-SCHEDULE-SUITE",
    name_ar: "تقارير الجداول (إسناد/غير مُسندة/مجموعات/جدول زمني/قاعات/عبء هيئة التدريس/تعارض)",
    description:
      "سبعة تقارير فرعية للجداول الدراسية؛ الوحيدة التي تمنح department_head وصولاً تقاريرياً على main (SCHEDULE_REPORT_ROLES).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "academic_affairs", "faculty_supervisor"],
    required_role: ["system_admin", "admin", "dean", "registrar", "department_head"],
    data_scope: "university/college/department",
    source:
      "جداول course_sections/class_schedule/rooms — 7 دوال get*ReportForAdmin في src/lib/admin-reports.functions.ts (SCHEDULE_REPORT_ROLES)",
    filters: ["academic_year_id", "semester_id", "department_id", "level_id"],
    sensitivity: "internal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: [],
    dependencies: [],
    status: "DATA_DEPENDENT",
    blocker: "لا اختبار مؤتمت مثبت",
    evidence: [
      "src/lib/admin-reports.functions.ts (SCHEDULE_REPORT_ROLES — تشمل department_head)",
      "src/routes/admin/reports.tsx (قسم schedules — ScheduleReports, 6 تبويبات + مؤشرات تعارض)",
    ],
  },
  {
    report_code: "ADM-STUDENT-REQUESTS",
    name_ar: "تقرير طلبات الطلاب",
    description:
      "طلبات الطلاب مع ترشيحات؛ القسم الوحيد من عائلة الدوال القديمة الموصول فعلاً بالواجهة، مع تدقيق عرض/تصدير (reportName: student_requests_report). يغطي بند §5 «طلبات الطلاب حسب الحالة».",
    beneficiaries: ["vp_student_affairs", "dean", "operational_units_staff"],
    required_role: ["system_admin", "admin", "dean", "registrar", "finance_officer", "student_affairs"],
    data_scope: "university",
    source:
      "table: student_requests — getReportsRequests (assertReportsAccess/REPORTS_ROLES) في src/lib/admin-reports.functions.ts",
    filters: ["status", "request_type", "date_range"],
    sensitivity: "personal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: [],
    dependencies: ["src/lib/reports/report-audit.functions.ts:logReportEvent", "rpc:log_audit"],
    status: "DATA_DEPENDENT",
    blocker: "لا اختبار مؤتمت مثبت",
    evidence: [
      "src/lib/admin-reports.functions.ts (getReportsRequests)",
      "src/routes/admin/reports.tsx (قسم requests — RequestsReport نشط)",
      "docs/REPORTS-REQUESTS-SECTION-01-REPORT.md",
    ],
  },
  {
    report_code: "EXEC-CORE-KPIS",
    name_ar: "لوحة المؤشرات التنفيذية للقيادة",
    description:
      "KPIs حية: طلاب/نشطون، هيئة تدريس، شعب، نسبة تحصيل الرسوم، طلاب بلا برنامج، شعب بلا إسناد، مرشحو تخرج معلقون، وثائق اليوم، طلبات معلقة، آخر حدث تدقيق — مع تدقيق مشاهدة اللوحة.",
    beneficiaries: ["university_presidency_council", "dean", "vp_academic_affairs", "vp_student_affairs"],
    required_role: ["admin", "system_admin", "dean", "registrar"],
    data_scope: "university (نطاق قسم لرئيس القسم عبر faculty_profiles)",
    source:
      "عدّ مباشر من جداول متعددة (student_profiles, faculty_profiles, course_sections, class_schedule, student_fees, student_requests, official_documents, audit_logs) — getExecutiveCoreKpis/getExecutiveScope/logExecutiveDashboardViewed في src/lib/executive-dashboard.functions.ts",
    filters: [],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: "/admin/executive-dashboard",
    tests: [],
    dependencies: ["src/lib/authz.server.ts:EXEC_ROLES", "rpc:log_audit"],
    status: "DATA_DEPENDENT",
    blocker: "اختبار مؤتمت غير مؤكد (لم يُعثر عليه في tests/admin)",
    evidence: [
      "src/lib/executive-dashboard.functions.ts",
      "src/routes/admin/executive-dashboard.lazy.tsx",
    ],
  },
  // ------------------------------------------------------------------
  // PR #192 aggregate builders + dashboards (no server fn, no route)
  // ------------------------------------------------------------------
  {
    report_code: "AGG-REQUESTS-OVERVIEW",
    name_ar: "نظرة مجمعة على طلبات الطلاب (aggregate-only)",
    description:
      "KPIs وجداول مجمعة (حسب النوع/البرنامج/المستوى/الحالة/عمر التعليق) مع حجب الخلايا الصغيرة والكتمان التكميلي ونسب آمنة. يغطي بند §5 «طلبات الطلاب حسب النوع/البرنامج/المستوى» وبند «الطلبات المتأخرة» (جدول pending_age).",
    beneficiaries: ["dean", "vp_student_affairs", "university_presidency_council"],
    required_role: ["dean", "student_affairs", "admin", "system_admin"],
    data_scope: "university",
    source:
      "builder: buildRequestsAggregateReport في src/lib/reports/request-reports.ts (مدخلات صفوف مجهولة الهوية يمررها المُستدعي — لا مستدعي إنتاجي)",
    filters: ["by_type", "by_program", "by_level", "by_status_group", "pending_age"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/reports/report-builders.test.ts"],
    dependencies: [
      "src/lib/reports/aggregate.ts",
      "src/components/dashboards/RequestsAggregateDashboard.tsx",
      "src/components/reports/AggregateReportView.tsx",
    ],
    status: "UNDER_DEVELOPMENT",
    blocker:
      "لا server function ولا route — التوصيل في /admin/reports متابعة لاحقة موثقة (§2.3/§5.8 من تقرير PR #192) + ربط assertAggregateReportSafe بمسار الانبعاث",
    evidence: [
      "src/lib/reports/request-reports.ts",
      "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "AGG-STAFF-ACTIVITY-BY-ROLE",
    name_ar: "نشاط المعالجة حسب الدور الوظيفي",
    description:
      "تجميع نشاط معالجة الطلبات على مستوى الدور لا الفرد (قرار حوكمة fail-closed) مع مصفوفة دور×إجراء وهوامش محمية.",
    beneficiaries: ["university_presidency_council", "dean"],
    required_role: ["admin", "system_admin", "dean"],
    data_scope: "university",
    source: "builder: buildStaffActivityReport في src/lib/reports/staff-activity-reports.ts",
    filters: ["by_role", "role_event_matrix", "event_groups"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/reports/report-builders.test.ts"],
    dependencies: ["src/lib/reports/aggregate.ts", "src/components/dashboards/StaffActivityDashboard.tsx"],
    status: "UNDER_DEVELOPMENT",
    blocker: "لا server function ولا route (موثق في تقرير PR #192)",
    evidence: [
      "src/lib/reports/staff-activity-reports.ts",
      "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "AGG-FINANCE-SUMMARY",
    name_ar: "الملخص المالي المجمع",
    description:
      "رسوم/مدفوعات/متبقٍ مجمعة (حسب النوع والفترة) بعقد aggregate-only؛ البديل العصري للدالة اليتيمة getReportsFinancial.",
    beneficiaries: ["university_presidency_council", "dean", "operational_units_staff"],
    required_role: ["finance_officer", "admin", "system_admin", "dean"],
    data_scope: "university",
    source: "builder: buildFinanceSummaryReport في src/lib/reports/finance-reports.ts",
    filters: ["by_kind", "by_period_count", "period_amounts"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/reports/report-builders.test.ts"],
    dependencies: ["src/lib/reports/aggregate.ts", "src/components/dashboards/FinanceAggregateDashboard.tsx"],
    status: "UNDER_DEVELOPMENT",
    blocker: "لا server function ولا route (موثق في تقرير PR #192)",
    evidence: [
      "src/lib/reports/finance-reports.ts",
      "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md",
    ],
  },
  // ------------------------------------------------------------------
  // Academic clearance family — §5 items 1..7 (SQL DRAFT-ONLY, no route)
  // ------------------------------------------------------------------
  {
    report_code: "CLR-REQUESTS-BY-STATUS",
    name_ar: "تقرير طلبات المقاصة حسب الحالة",
    description:
      "بند §5-1 من عائلة المقاصة: عدّ طلبات المقاصة بحسب الحالات السبع المغلقة (بما فيها returned/rejected) عبر عرض academic_clearance_reporting.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "dean"],
    required_role: ["pending:clearance_sql_roles (رئيس القسم المستهدف + وحدة الشؤون الأكاديمية — صف config وحيد)"],
    data_scope: "department/university",
    source:
      "VIEW (DRAFT-ONLY): academic_clearance_reporting + summarizeClearanceReporting في src/lib/academic-clearance.ts",
    filters: ["status"],
    sensitivity: "personal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql",
      "docs/migration-drafts/DEPARTMENT-TRANSFER-ACADEMIC-CLEARANCE-FOUNDATION-01.sql",
    ],
    status: "BLOCKED",
    blocker:
      "مسودتا SQL (أساس + استكمال) غير مطبقتين + لا route (routes مملوكة لـ Q-13) + صف إعدادات الجهة (singleton) غير مكوَّن",
    evidence: [
      "src/lib/academic-clearance.ts (summarizeClearanceReporting)",
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "CLR-COURSE-OUTCOMES",
    name_ar: "تقرير مقررات المقاصة المقبولة والمرفوضة (وأكثر المقررات قبولاً/رفضاً)",
    description:
      "بندا §5-2 و§5-5 من عائلة المقاصة (مدمجان لتقاربهما): نتائج المقررات بالقرارات السبعة (مقررات مقبولة ومرفوضة) مع ترتيب أكثر المقررات قبولاً أو رفضاً، عبر عرض academic_clearance_course_outcomes (يستثني general_requirement).",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "dean"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "department/university",
    source:
      "VIEW (DRAFT-ONLY): academic_clearance_course_outcomes + summarizeCourseOutcomes في src/lib/academic-clearance.ts",
    filters: ["decision", "course_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "src/components/academic-clearance/CourseComparison.tsx",
      "docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودتا SQL غير مطبقتين + لا route (routes مملوكة لـ Q-13)",
    evidence: [
      "src/lib/academic-clearance.ts (summarizeCourseOutcomes)",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "CLR-EQUIVALENCY-HOURS",
    name_ar: "تقرير الساعات المعادلة والمتبقية",
    description:
      "بند §5-3 من عائلة المقاصة: إجمالي الساعات المعادلة والمتبقية لكل حالة/طالب — لا عرض ولا باني مخصص على main؛ يُشتق من قرارات المعادلة بعد تطبيق المسودة.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "student"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "case-level/department",
    source: "لا مصدر تقرير مخصص على main — مشتق مخطط من قرارات المعادلة (docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql)",
    filters: ["clearance_case_id", "department_id"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql", "src/lib/academic-clearance.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا باني/عرض مخصص للساعات + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "CLR-OVERDUE-STOP-POINT",
    name_ar: "تقرير طلبات المقاصة المتأخرة وجهة التوقف",
    description:
      "بند §5-4 من عائلة المقاصة: الطلبات المتجاوزة لنافذة التأخر (14 يوماً) مع جهة التوقف الحالية في مسار الاعتمادات.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "dean"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "department/university",
    source:
      "VIEW (DRAFT-ONLY): academic_clearance_reporting (نافذة التأخر 14 يوماً) + summarizeClearanceReporting في src/lib/academic-clearance.ts",
    filters: ["overdue_window_14d", "pending_at"],
    sensitivity: "personal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "src/components/academic-clearance/ClearanceApprovalsTimeline.tsx",
    ],
    status: "BLOCKED",
    blocker: "مسودتا SQL غير مطبقتين + لا route (routes مملوكة لـ Q-13)",
    evidence: [
      "src/lib/academic-clearance.ts",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "CLR-SUGGESTED-LEVEL",
    name_ar: "تقرير المستوى المقترح بعد المعادلة",
    description:
      "بند §5-6 من عائلة المقاصة: اقتراح المستوى الدراسي للطالب المحوَّل بناءً على الساعات المعادلة — لا مصدر على main إطلاقاً.",
    beneficiaries: ["academic_affairs", "vp_academic_affairs", "dept_head_coordinator"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "case-level",
    source: "لا مصدر تقرير على main — يتطلب قاعدة اشتقاق مستوى من قرارات المعادلة (غير منشأة)",
    filters: ["clearance_case_id"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql"],
    status: "NOT_ACTIVATED",
    blocker: "قاعدة اشتقاق المستوى المقترح غير معرفة + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "CLR-EQUIVALENCY-MINUTES",
    name_ar: "محضر المعادلات واعتماداته النهائية",
    description:
      "بند §5-7 من عائلة المقاصة: محضر موثق بقرارات المعادلة السبعة لكل مقرر + خط زمني للاعتمادات (append-only) — مخرج عملية المقاصة الرسمي.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "student"],
    required_role: ["pending:clearance_sql_roles (قراءة الطالب بعد الاعتماد الكامل = قرار منتج معلق)"],
    data_scope: "case-level",
    source: "buildClearanceMinutes في src/lib/academic-clearance.ts + جداول approvals/audit (append-only)",
    filters: ["clearance_case_id"],
    sensitivity: "personal",
    output_types: ["screen", "pdf"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceMinutes.tsx",
      "src/components/academic-clearance/ClearanceApprovalsTimeline.tsx",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route + عرض المحضر للطالب يتطلب قرار منتج",
    evidence: [
      "src/lib/academic-clearance.ts (buildClearanceMinutes)",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  // ------------------------------------------------------------------
  // Graduation projects family — §5 items 1..8
  // ------------------------------------------------------------------
  {
    report_code: "GP-DEPT-STATES",
    name_ar: "تقرير حالات مشاريع التخرج (قسم)",
    description: "بند §5-1 من عائلة مشاريع التخرج: توزيع حالات مشاريع التخرج على مستوى القسم.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "academic_affairs"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_states_report — عميل getStatesReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/ (42 اختباراً — PR #190)"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة على قاعدة البيانات (DRAFT ONLY) + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getStatesReport)",
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-DEPT-ASSIGNMENTS",
    name_ar: "تقرير تعيينات مشاريع التخرج (قسم)",
    description: "بند §5-2 من عائلة مشاريع التخرج: تعيينات الإشراف/التنسيق/اللجان على مشاريع القسم.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_assignments_report — عميل getAssignmentsReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getAssignmentsReport)",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-DEPT-EVALUATIONS",
    name_ar: "تقرير تقييمات مشاريع التخرج (قسم)",
    description: "بند §5-3 من عائلة مشاريع التخرج: نتائج تقييمات اللجان لمشاريع القسم.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "alumni_quality"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_evaluations_report — عميل getEvaluationsReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "personal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getEvaluationsReport)",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-DEPT-ARCHIVE",
    name_ar: "تقرير أرشيف مشاريع التخرج (قسم)",
    description:
      "بند §5-4 من عائلة مشاريع التخرج: المشاريع المؤرشفة وجاهزية الأرشفة (ملف نهائي مقبول + تصحيحات مقبولة).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "academic_affairs"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_archive_report — عميل getArchiveReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getArchiveReport)",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-SUPERVISOR-LOAD",
    name_ar: "تقرير عبء الإشراف على مشاريع التخرج",
    description:
      "بند §5-5 من عائلة مشاريع التخرج: عدد المشاريع لكل مشرف/عضو هيئة تدريس — لا مصدر تقرير مخصص على main (تقرير التعيينات جزئية أقرب).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "department/college",
    source: "لا مصدر تقرير مخصص على main — أقرب جزئية: get_graduation_project_assignments_report (DRAFT-ONLY)",
    filters: ["department_id", "semester_id"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduation-projects/rpc.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا باني/RPC مخصص لعبء الإشراف + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "GP-TIMELINE-STATUS",
    name_ar: "تقرير المراحل والمواعيد المتأخرة لمشاريع التخرج",
    description:
      "بند §5-6 من عائلة مشاريع التخرج: تتبع مراحل دورة الحياة والمشاريع المتأخرة عن مواعيدها — لا مصدر تقرير على main.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "department",
    source: "لا مصدر تقرير على main — دورة الحياة موجودة (PR #190) لكن لا تقرير مراحل/تأخر",
    filters: ["department_id", "stage", "overdue"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduation-projects/rpc.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا تقرير مراحل/تأخر منشأ + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "GP-DEFENSE-OUTCOMES",
    name_ar: "تقرير نتائج المناقشات والدرجات",
    description:
      "بند §5-7 من عائلة مشاريع التخرج: نتائج المناقشات وتوزيع الدرجات — لا مصدر مخصص؛ تقرير التقييمات (قسم) جزئية أقرب.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "alumni_quality"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "department/college",
    source: "لا مصدر تقرير مخصص على main — أقرب جزئية: get_graduation_project_evaluations_report (DRAFT-ONLY)",
    filters: ["department_id", "semester_id"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduation-projects/rpc.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا تقرير نتائج/درجات منشأ + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "GP-UNIVERSITY-SUMMARY",
    name_ar: "الملخص الجامعي لمشاريع التخرج",
    description:
      "بند §5-8 من عائلة مشاريع التخرج: ملخص مجمع على مستوى الجامعة/الكليات (أعداد/حالات/إنجاز) للقيادة — تقارير القسم الأربعة نطاقها قسم فقط.",
    beneficiaries: ["university_presidency_council", "vp_academic_affairs", "dean"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "university",
    source: "لا مصدر تقرير على main — تقارير القسم (DRAFT-ONLY) لا تغطي المستوى الجامعي",
    filters: ["college_id", "semester_id"],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql"],
    status: "NOT_ACTIVATED",
    blocker: "لا عرض جامعي مجمع + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
