/**
 * The canonical portal reports catalog.
 *
 * Every entry is evidence-anchored to paths on `main` (see INVENTORY.md basis:
 * PORTAL-REPORTS-CANONICAL-CATALOG-AND-TRACEABILITY-01 inventory, head
 * 0e2d25c9; re-verified at branch time against 1cedb888). Status decisions
 * follow the strict rules documented in
 * docs/PORTAL-REPORTS-CANONICAL-CATALOG-AND-TRACEABILITY-01-REPORT.md:
 * LIVE requires source + permission + route + automated test + real wiring,
 * all proven by file paths. Track
 * ADMIN-REPORTS-TEST-HARDENING-AND-CATALOG-RECONCILIATION-01 added the
 * automated test pillar (`tests/admin-reports/**`) for the six wired
 * `/admin/reports` sections and promoted them DATA_DEPENDENT -> LIVE after
 * verifying all five proofs; EXEC-CORE-KPIS remains DATA_DEPENDENT
 * (out of scope, documented follow-up).
 */

import type { ReportEntry } from "./types";

export const REPORT_CATALOG_ENTRIES: readonly ReportEntry[] = [
  // ------------------------------------------------------------------
  // Wired admin report sections (source + guard + route + wiring; no tests)
  // ------------------------------------------------------------------
  {
    report_code: "ADM-STUDENTS-DIRECTORY",
    name_ar: "تقرير دليل الطلاب",
    description:
      "قائمة الطلاب مع ترشيحات (نظام الدراسة/قسم/برنامج/مستوى/سنة/فصل/حالة/حالة حساب) وترقيم صفحات، مع تصدير CSV/XLSX.",
    beneficiaries: ["dean", "operational_units_staff", "vp_student_affairs", "vp_academic_affairs"],
    required_role: ["admin", "system_admin", "dean", "registrar", "student_affairs"],
    data_scope: "university",
    source:
      "table: student_profiles (عبر supabaseAdmin) — getStudentsReportForAdmin في src/lib/admin-reports.functions.ts",
    filters: ["study_system", "department_id", "program_id", "level_id", "academic_year_id", "semester_id", "status", "account_status", "page", "pageSize"],
    sensitivity: "personal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: ["tests/admin-reports/ui-states-and-filters.test.ts", "tests/admin-reports/privacy-and-export-scope.test.ts", "tests/admin-reports/catalog-compat.test.ts"],
    dependencies: ["src/lib/authz.server.ts:assertStudentRead", "src/lib/reports/export.ts"],
    status: "LIVE",
    blocker: null,
    evidence: [
      "src/lib/admin-reports.functions.ts (getStudentsReportForAdmin)",
      "src/routes/admin/reports.tsx (قسم students — StudentsReport)",
      "tests/admin-reports/ (Track G hardening tests)",
    ],
  },
  {
    report_code: "ADM-IMPORT-JOBS",
    name_ar: "تقرير مهام الاستيراد وأخطاؤها",
    description: "متابعة مهام استيراد البيانات مع تفصيل أخطاء كل مهمة.",
    beneficiaries: ["operational_units_staff", "vp_academic_affairs", "dean"],
    required_role: ["admin", "system_admin", "registrar", "student_affairs", "finance_officer"],
    data_scope: "university",
    source:
      "جداول مهام الاستيراد — getImportJobsReportForAdmin / getImportJobErrorsForAdmin في src/lib/admin-reports.functions.ts (IMPORT_REPORT_ROLES)",
    filters: ["job_status", "job_type"],
    sensitivity: "internal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: ["tests/admin-reports/guards-and-visibility.test.ts", "tests/admin-reports/catalog-compat.test.ts"],
    dependencies: ["src/lib/imports/ (PR #193/#195)"],
    status: "LIVE",
    blocker: null,
    evidence: [
      "src/lib/admin-reports.functions.ts (getImportJobsReportForAdmin/getImportJobErrorsForAdmin)",
      "src/routes/admin/reports.tsx (قسم imports — ImportJobsReport)",
    ],
  },
  {
    report_code: "ADM-STUDENT-ACCOUNTS",
    name_ar: "تقرير حسابات الطلاب",
    description: "حالة حسابات الدخول للطلاب (من لديه حساب/بدون).",
    beneficiaries: ["operational_units_staff", "vp_student_affairs", "dean"],
    required_role: ["system_admin", "admin", "dean", "registrar", "student_affairs"],
    data_scope: "university",
    source:
      "جدول student_profiles/حسابات — getStudentAccountsReportForAdmin في src/lib/admin-reports.functions.ts (assertStudentRead / STUDENT_READ_ROLES)",
    filters: ["account_status", "department_id"],
    sensitivity: "personal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: ["tests/admin-reports/guards-and-visibility.test.ts", "tests/admin-reports/catalog-compat.test.ts"],
    dependencies: ["src/lib/authz.server.ts:assertStudentRead"],
    status: "LIVE",
    blocker: null,
    evidence: [
      "src/lib/admin-reports.functions.ts (getStudentAccountsReportForAdmin)",
      "src/routes/admin/reports.tsx (قسم accounts — StudentAccountsReport)",
    ],
  },
  {
    report_code: "ADM-ACADEMIC-STRUCTURE",
    name_ar: "التقارير الأكاديمية (برامج/خطط دراسية/مقررات/تغطية الخطط)",
    description: "أربعة تقارير فرعية عن الهيكل الأكاديمي وتغطية الخطط الدراسية ضمن قسم academic.",
    beneficiaries: ["vp_academic_affairs", "dean", "academic_affairs", "dept_head_coordinator"],
    required_role: ["system_admin", "admin", "dean", "registrar", "finance_officer", "student_affairs"],
    data_scope: "university",
    source:
      "جداول programs/study_plans/courses — getAcademicProgramsReportForAdmin + getStudyPlansReportForAdmin + getCoursesReportForAdmin + getStudyPlanCoverageReportForAdmin في src/lib/admin-reports.functions.ts",
    filters: ["department_id", "program_id"],
    sensitivity: "internal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: ["tests/admin-reports/ui-states-and-filters.test.ts", "tests/admin-reports/privacy-and-export-scope.test.ts", "tests/admin-reports/catalog-compat.test.ts"],
    dependencies: ["src/lib/admin-reports.functions.ts:getAcademicReportLookupsForAdmin"],
    status: "LIVE",
    blocker: null,
    evidence: [
      "src/lib/admin-reports.functions.ts (getAcademic*ReportForAdmin ×4)",
      "src/routes/admin/reports.tsx (قسم academic — AcademicReports)",
    ],
  },
  {
    report_code: "ADM-SCHEDULE-SUITE",
    name_ar: "تقارير الجداول (إسناد/غير مُسندة/مجموعات/جدول زمني/قاعات/عبء هيئة التدريس/تعارض)",
    description:
      "سبعة تقارير فرعية للجداول الدراسية؛ الوحيدة التي تمنح department_head وصولاً تقاريرياً على main (SCHEDULE_REPORT_ROLES).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "academic_affairs", "faculty_supervisor"],
    required_role: ["system_admin", "admin", "dean", "registrar", "department_head"],
    data_scope: "university/college/department",
    source:
      "جداول course_sections/class_schedule/rooms — 7 دوال get*ReportForAdmin في src/lib/admin-reports.functions.ts (SCHEDULE_REPORT_ROLES)",
    filters: ["academic_year_id", "semester_id", "department_id", "level_id"],
    sensitivity: "internal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: ["tests/admin-reports/guards-and-visibility.test.ts", "tests/admin-reports/catalog-compat.test.ts"],
    dependencies: [],
    status: "LIVE",
    blocker: null,
    evidence: [
      "src/lib/admin-reports.functions.ts (SCHEDULE_REPORT_ROLES — تشمل department_head)",
      "src/routes/admin/reports.tsx (قسم schedules — ScheduleReports, 6 تبويبات + مؤشرات تعارض)",
    ],
  },
  {
    report_code: "ADM-STUDENT-REQUESTS",
    name_ar: "تقرير طلبات الطلاب",
    description:
      "طلبات الطلاب مع ترشيحات؛ القسم الوحيد من عائلة الدوال القديمة الموصول فعلاً بالواجهة، مع تدقيق عرض/تصدير (reportName: student_requests_report). يغطي بند §5 «طلبات الطلاب حسب الحالة».",
    beneficiaries: ["vp_student_affairs", "dean", "operational_units_staff"],
    required_role: ["system_admin", "admin", "dean", "registrar", "finance_officer", "student_affairs"],
    data_scope: "university",
    source:
      "table: student_requests — getReportsRequests (assertReportsAccess/REPORTS_ROLES) في src/lib/admin-reports.functions.ts",
    filters: ["status", "request_type", "date_range"],
    sensitivity: "personal",
    output_types: ["screen", "excel"],
    route: "/admin/reports",
    tests: ["tests/admin-reports/ui-states-and-filters.test.ts", "tests/admin-reports/privacy-and-export-scope.test.ts", "tests/admin-reports/catalog-compat.test.ts"],
    dependencies: ["src/lib/reports/report-audit.functions.ts:logReportEvent", "rpc:log_audit"],
    status: "LIVE",
    blocker: null,
    evidence: [
      "src/lib/admin-reports.functions.ts (getReportsRequests)",
      "src/routes/admin/reports.tsx (قسم requests — RequestsReport نشط)",
      "docs/REPORTS-REQUESTS-SECTION-01-REPORT.md",
    ],
  },
  {
    report_code: "EXEC-CORE-KPIS",
    name_ar: "لوحة المؤشرات التنفيذية للقيادة",
    description:
      "KPIs حية: طلاب/نشطون، هيئة تدريس، شعب، نسبة تحصيل الرسوم، طلاب بلا برنامج، شعب بلا إسناد، مرشحو تخرج معلقون، وثائق اليوم، طلبات معلقة، آخر حدث تدقيق — مع تدقيق مشاهدة اللوحة.",
    beneficiaries: ["university_presidency_council", "dean", "vp_academic_affairs", "vp_student_affairs"],
    required_role: ["admin", "system_admin", "dean", "registrar"],
    data_scope: "university (نطاق قسم لرئيس القسم عبر faculty_profiles)",
    source:
      "عدّ مباشر من جداول متعددة (student_profiles, faculty_profiles, course_sections, class_schedule, student_fees, student_requests, official_documents, audit_logs) — getExecutiveCoreKpis/getExecutiveScope/logExecutiveDashboardViewed في src/lib/executive-dashboard.functions.ts",
    filters: [],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: "/admin/executive-dashboard",
    tests: [],
    dependencies: ["src/lib/authz.server.ts:EXEC_ROLES", "rpc:log_audit"],
    status: "DATA_DEPENDENT",
    blocker: "اختبار مؤتمت غير مؤكد (لم يُعثر عليه في tests/admin)",
    evidence: [
      "src/lib/executive-dashboard.functions.ts",
      "src/routes/admin/executive-dashboard.lazy.tsx",
    ],
  },
  // ------------------------------------------------------------------
  // PR #192 aggregate builders + dashboards (no server fn, no route)
  // ------------------------------------------------------------------
  {
    report_code: "AGG-REQUESTS-OVERVIEW",
    name_ar: "نظرة مجمعة على طلبات الطلاب (aggregate-only)",
    description:
      "KPIs وجداول مجمعة (حسب النوع/البرنامج/المستوى/الحالة/عمر التعليق) مع حجب الخلايا الصغيرة والكتمان التكميلي ونسب آمنة. يغطي بند §5 «طلبات الطلاب حسب النوع/البرنامج/المستوى» وبند «الطلبات المتأخرة» (جدول pending_age).",
    beneficiaries: ["dean", "vp_student_affairs", "university_presidency_council"],
    required_role: ["dean", "student_affairs", "admin", "system_admin"],
    data_scope: "university",
    source:
      "builder: buildRequestsAggregateReport في src/lib/reports/request-reports.ts (مدخلات صفوف مجهولة الهوية يمررها المُستدعي — لا مستدعي إنتاجي)",
    filters: ["by_type", "by_program", "by_level", "by_status_group", "pending_age"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/reports/report-builders.test.ts"],
    dependencies: [
      "src/lib/reports/aggregate.ts",
      "src/components/dashboards/RequestsAggregateDashboard.tsx",
      "src/components/reports/AggregateReportView.tsx",
    ],
    status: "UNDER_DEVELOPMENT",
    blocker:
      "لا server function ولا route — التوصيل في /admin/reports متابعة لاحقة موثقة (§2.3/§5.8 من تقرير PR #192) + ربط assertAggregateReportSafe بمسار الانبعاث",
    evidence: [
      "src/lib/reports/request-reports.ts",
      "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "AGG-STAFF-ACTIVITY-BY-ROLE",
    name_ar: "نشاط المعالجة حسب الدور الوظيفي",
    description:
      "تجميع نشاط معالجة الطلبات على مستوى الدور لا الفرد (قرار حوكمة fail-closed) مع مصفوفة دور×إجراء وهوامش محمية.",
    beneficiaries: ["university_presidency_council", "dean"],
    required_role: ["admin", "system_admin", "dean"],
    data_scope: "university",
    source: "builder: buildStaffActivityReport في src/lib/reports/staff-activity-reports.ts",
    filters: ["by_role", "role_event_matrix", "event_groups"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/reports/report-builders.test.ts"],
    dependencies: ["src/lib/reports/aggregate.ts", "src/components/dashboards/StaffActivityDashboard.tsx"],
    status: "UNDER_DEVELOPMENT",
    blocker: "لا server function ولا route (موثق في تقرير PR #192)",
    evidence: [
      "src/lib/reports/staff-activity-reports.ts",
      "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "AGG-FINANCE-SUMMARY",
    name_ar: "الملخص المالي المجمع",
    description:
      "رسوم/مدفوعات/متبقٍ مجمعة (حسب النوع والفترة) بعقد aggregate-only؛ البديل العصري للدالة اليتيمة getReportsFinancial.",
    beneficiaries: ["university_presidency_council", "dean", "operational_units_staff"],
    required_role: ["finance_officer", "admin", "system_admin", "dean"],
    data_scope: "university",
    source: "builder: buildFinanceSummaryReport في src/lib/reports/finance-reports.ts",
    filters: ["by_kind", "by_period_count", "period_amounts"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/reports/report-builders.test.ts"],
    dependencies: ["src/lib/reports/aggregate.ts", "src/components/dashboards/FinanceAggregateDashboard.tsx"],
    status: "UNDER_DEVELOPMENT",
    blocker: "لا server function ولا route (موثق في تقرير PR #192)",
    evidence: [
      "src/lib/reports/finance-reports.ts",
      "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md",
    ],
  },
  // ------------------------------------------------------------------
  // Academic clearance family — §5 items 1..7 (SQL DRAFT-ONLY, no route)
  // ------------------------------------------------------------------
  {
    report_code: "CLR-REQUESTS-BY-STATUS",
    name_ar: "تقرير طلبات المقاصة حسب الحالة",
    description:
      "بند §5-1 من عائلة المقاصة: عدّ طلبات المقاصة بحسب الحالات السبع المغلقة (بما فيها returned/rejected) عبر عرض academic_clearance_reporting.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "dean"],
    required_role: ["pending:clearance_sql_roles (رئيس القسم المستهدف + وحدة الشؤون الأكاديمية — صف config وحيد)"],
    data_scope: "department/university",
    source:
      "VIEW (DRAFT-ONLY): academic_clearance_reporting + summarizeClearanceReporting في src/lib/academic-clearance.ts",
    filters: ["status"],
    sensitivity: "personal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql",
      "docs/migration-drafts/DEPARTMENT-TRANSFER-ACADEMIC-CLEARANCE-FOUNDATION-01.sql",
    ],
    status: "BLOCKED",
    blocker:
      "مسودتا SQL (أساس + استكمال) غير مطبقتين + لا route (routes مملوكة لـ Q-13) + صف إعدادات الجهة (singleton) غير مكوَّن",
    evidence: [
      "src/lib/academic-clearance.ts (summarizeClearanceReporting)",
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "CLR-COURSE-OUTCOMES",
    name_ar: "تقرير مقررات المقاصة المقبولة والمرفوضة (وأكثر المقررات قبولاً/رفضاً)",
    description:
      "بندا §5-2 و§5-5 من عائلة المقاصة (مدمجان لتقاربهما): نتائج المقررات بالقرارات السبعة (مقررات مقبولة ومرفوضة) مع ترتيب أكثر المقررات قبولاً أو رفضاً، عبر عرض academic_clearance_course_outcomes (يستثني general_requirement).",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "dean"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "department/university",
    source:
      "VIEW (DRAFT-ONLY): academic_clearance_course_outcomes + summarizeCourseOutcomes في src/lib/academic-clearance.ts",
    filters: ["decision", "course_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "src/components/academic-clearance/CourseComparison.tsx",
      "docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودتا SQL غير مطبقتين + لا route (routes مملوكة لـ Q-13)",
    evidence: [
      "src/lib/academic-clearance.ts (summarizeCourseOutcomes)",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "CLR-EQUIVALENCY-HOURS",
    name_ar: "تقرير الساعات المعادلة والمتبقية",
    description:
      "بند §5-3 من عائلة المقاصة: إجمالي الساعات المعادلة والمتبقية لكل حالة/طالب — لا عرض ولا باني مخصص على main؛ يُشتق من قرارات المعادلة بعد تطبيق المسودة.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "student"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "case-level/department",
    source: "لا مصدر تقرير مخصص على main — مشتق مخطط من قرارات المعادلة (docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql)",
    filters: ["clearance_case_id", "department_id"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql", "src/lib/academic-clearance.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا باني/عرض مخصص للساعات + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "CLR-OVERDUE-STOP-POINT",
    name_ar: "تقرير طلبات المقاصة المتأخرة وجهة التوقف",
    description:
      "بند §5-4 من عائلة المقاصة: الطلبات المتجاوزة لنافذة التأخر (14 يوماً) مع جهة التوقف الحالية في مسار الاعتمادات.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "dean"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "department/university",
    source:
      "VIEW (DRAFT-ONLY): academic_clearance_reporting (نافذة التأخر 14 يوماً) + summarizeClearanceReporting في src/lib/academic-clearance.ts",
    filters: ["overdue_window_14d", "pending_at"],
    sensitivity: "personal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceReporting.tsx",
      "src/components/academic-clearance/ClearanceApprovalsTimeline.tsx",
    ],
    status: "BLOCKED",
    blocker: "مسودتا SQL غير مطبقتين + لا route (routes مملوكة لـ Q-13)",
    evidence: [
      "src/lib/academic-clearance.ts",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "CLR-SUGGESTED-LEVEL",
    name_ar: "تقرير المستوى المقترح بعد المعادلة",
    description:
      "بند §5-6 من عائلة المقاصة: اقتراح المستوى الدراسي للطالب المحوَّل بناءً على الساعات المعادلة — لا مصدر على main إطلاقاً.",
    beneficiaries: ["academic_affairs", "vp_academic_affairs", "dept_head_coordinator"],
    required_role: ["pending:clearance_sql_roles"],
    data_scope: "case-level",
    source: "لا مصدر تقرير على main — يتطلب قاعدة اشتقاق مستوى من قرارات المعادلة (غير منشأة)",
    filters: ["clearance_case_id"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/drafts/ACADEMIC-CLEARANCE-COMPLETION-01.sql"],
    status: "NOT_ACTIVATED",
    blocker: "قاعدة اشتقاق المستوى المقترح غير معرفة + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "CLR-EQUIVALENCY-MINUTES",
    name_ar: "محضر المعادلات واعتماداته النهائية",
    description:
      "بند §5-7 من عائلة المقاصة: محضر موثق بقرارات المعادلة السبعة لكل مقرر + خط زمني للاعتمادات (append-only) — مخرج عملية المقاصة الرسمي.",
    beneficiaries: ["academic_affairs", "dept_head_coordinator", "vp_academic_affairs", "student"],
    required_role: ["pending:clearance_sql_roles (قراءة الطالب بعد الاعتماد الكامل = قرار منتج معلق)"],
    data_scope: "case-level",
    source: "buildClearanceMinutes في src/lib/academic-clearance.ts + جداول approvals/audit (append-only)",
    filters: ["clearance_case_id"],
    sensitivity: "personal",
    output_types: ["screen", "pdf"],
    route: null,
    tests: ["tests/academic-clearance/"],
    dependencies: [
      "src/components/academic-clearance/ClearanceMinutes.tsx",
      "src/components/academic-clearance/ClearanceApprovalsTimeline.tsx",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route + عرض المحضر للطالب يتطلب قرار منتج",
    evidence: [
      "src/lib/academic-clearance.ts (buildClearanceMinutes)",
      "docs/ACADEMIC-CLEARANCE-COMPLETION-01-REPORT.md",
    ],
  },
  // ------------------------------------------------------------------
  // Graduation projects family — §5 items 1..8
  // ------------------------------------------------------------------
  {
    report_code: "GP-DEPT-STATES",
    name_ar: "تقرير حالات مشاريع التخرج (قسم)",
    description: "بند §5-1 من عائلة مشاريع التخرج: توزيع حالات مشاريع التخرج على مستوى القسم.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "academic_affairs"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_states_report — عميل getStatesReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/ (42 اختباراً — PR #190)"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة على قاعدة البيانات (DRAFT ONLY) + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getStatesReport)",
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-DEPT-ASSIGNMENTS",
    name_ar: "تقرير تعيينات مشاريع التخرج (قسم)",
    description: "بند §5-2 من عائلة مشاريع التخرج: تعيينات الإشراف/التنسيق/اللجان على مشاريع القسم.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_assignments_report — عميل getAssignmentsReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getAssignmentsReport)",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-DEPT-EVALUATIONS",
    name_ar: "تقرير تقييمات مشاريع التخرج (قسم)",
    description: "بند §5-3 من عائلة مشاريع التخرج: نتائج تقييمات اللجان لمشاريع القسم.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "alumni_quality"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_evaluations_report — عميل getEvaluationsReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "personal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getEvaluationsReport)",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-DEPT-ARCHIVE",
    name_ar: "تقرير أرشيف مشاريع التخرج (قسم)",
    description:
      "بند §5-4 من عائلة مشاريع التخرج: المشاريع المؤرشفة وجاهزية الأرشفة (ملف نهائي مقبول + تصحيحات مقبولة).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "academic_affairs"],
    required_role: ["department_assignment:administrative_in_department"],
    data_scope: "department",
    source:
      "RPC (DRAFT-ONLY): get_graduation_project_archive_report — عميل getArchiveReport في src/lib/graduation-projects/rpc.ts",
    filters: ["department_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduation-projects/"],
    dependencies: [
      "src/components/graduation-projects/GraduationProjectReports.tsx",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route",
    evidence: [
      "src/lib/graduation-projects/rpc.ts (getArchiveReport)",
      "docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "GP-SUPERVISOR-LOAD",
    name_ar: "تقرير عبء الإشراف على مشاريع التخرج",
    description:
      "بند §5-5 من عائلة مشاريع التخرج: عدد المشاريع لكل مشرف/عضو هيئة تدريس — لا مصدر تقرير مخصص على main (تقرير التعيينات جزئية أقرب).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "department/college",
    source: "لا مصدر تقرير مخصص على main — أقرب جزئية: get_graduation_project_assignments_report (DRAFT-ONLY)",
    filters: ["department_id", "semester_id"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduation-projects/rpc.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا باني/RPC مخصص لعبء الإشراف + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "GP-TIMELINE-STATUS",
    name_ar: "تقرير المراحل والمواعيد المتأخرة لمشاريع التخرج",
    description:
      "بند §5-6 من عائلة مشاريع التخرج: تتبع مراحل دورة الحياة والمشاريع المتأخرة عن مواعيدها — لا مصدر تقرير على main.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "department",
    source: "لا مصدر تقرير على main — دورة الحياة موجودة (PR #190) لكن لا تقرير مراحل/تأخر",
    filters: ["department_id", "stage", "overdue"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduation-projects/rpc.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا تقرير مراحل/تأخر منشأ + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "GP-DEFENSE-OUTCOMES",
    name_ar: "تقرير نتائج المناقشات والدرجات",
    description:
      "بند §5-7 من عائلة مشاريع التخرج: نتائج المناقشات وتوزيع الدرجات — لا مصدر مخصص؛ تقرير التقييمات (قسم) جزئية أقرب.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "alumni_quality"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "department/college",
    source: "لا مصدر تقرير مخصص على main — أقرب جزئية: get_graduation_project_evaluations_report (DRAFT-ONLY)",
    filters: ["department_id", "semester_id"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduation-projects/rpc.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا تقرير نتائج/درجات منشأ + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "GP-UNIVERSITY-SUMMARY",
    name_ar: "الملخص الجامعي لمشاريع التخرج",
    description:
      "بند §5-8 من عائلة مشاريع التخرج: ملخص مجمع على مستوى الجامعة/الكليات (أعداد/حالات/إنجاز) للقيادة — تقارير القسم الأربعة نطاقها قسم فقط.",
    beneficiaries: ["university_presidency_council", "vp_academic_affairs", "dean"],
    required_role: ["pending:graduation_projects_report_roles"],
    data_scope: "university",
    source: "لا مصدر تقرير على main — تقارير القسم (DRAFT-ONLY) لا تغطي المستوى الجامعي",
    filters: ["college_id", "semester_id"],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/migration-drafts/GRADUATION-PROJECTS-LIFECYCLE-COMPLETION-01.sql"],
    status: "NOT_ACTIVATED",
    blocker: "لا عرض جامعي مجمع + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/GRADUATION-PROJECTS-COMPLETION-01-REPORT.md"],
  },
  // ------------------------------------------------------------------
  // Graduates family — §5 items 1..9
  // ------------------------------------------------------------------
  {
    report_code: "ALU-COHORT-EMPLOYMENT",
    name_ar: "تقرير أفواج توظيف الخريجين (برنامج×سنة)",
    description:
      "بند §5-1 من عائلة الخريجين: تقرير مجمع غير شخصي لتوظيف الخريجين بحسب الفوج مع حجب كل خلية دون العتبة (افتراضي 5) وفحص أمان التجميع.",
    beneficiaries: ["alumni_quality", "dean", "vp_academic_affairs", "university_presidency_council"],
    required_role: ["pending:g4_authorization_package (غير محسومة)"],
    data_scope: "university/college/program cohorts",
    source:
      "RPC (DRAFT-ONLY): graduate_aggregate_employment_report + buildCohortEmploymentReports/assertAggregateReportSafe في src/lib/graduates-affairs/reports.ts",
    filters: ["program_id", "graduation_year"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduates-affairs/ (29 اختباراً)"],
    dependencies: [
      "src/components/graduates-affairs/GraduateReportsPanel.tsx",
      "docs/migration-drafts/GRADUATES-AFFAIRS-MVP-COMPLETION-01.sql",
    ],
    status: "BLOCKED",
    blocker:
      "مسودة SQL غير مطبقة + لا route + حزمة تفويض G4 (RLS/EXECUTE/مصفوفة أدوار) معلقة + قرار D-13 (استمرارية الحساب) NEEDS_USER_INPUT",
    evidence: [
      "src/lib/graduates-affairs/reports.ts",
      "docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md",
      "docs/migration-drafts/GRADUATES-AFFAIRS-MVP-COMPLETION-01.sql",
    ],
  },
  {
    report_code: "ALU-SURVEY-AGGREGATES",
    name_ar: "تجميعات استبيانات الخريجين (وشيكة الأهلية)",
    description:
      "بندا §5-2 و§5-6 من عائلة الخريجين (مدمجان): تجميع نتائج استبيانات الخريجين (answers-only بنيوياً) + أهلية الاستبيان المربوطة بالموافقة.",
    beneficiaries: ["alumni_quality", "dean", "vp_academic_affairs"],
    required_role: ["pending:g4_authorization_package"],
    data_scope: "university",
    source: "aggregateSurveyResponses في src/lib/graduates-affairs/surveys.ts (+ عقود consents/communications)",
    filters: ["survey_id", "cohort"],
    sensitivity: "restricted",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduates-affairs/"],
    dependencies: ["src/components/graduates-affairs/GraduateSurveyCard.tsx"],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route + حزمة تفويض G4 + قوالب الرسائل (قرار محتوى)",
    evidence: [
      "src/lib/graduates-affairs/surveys.ts",
      "docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "ALU-GRADUATE-REGISTRY",
    name_ar: "تقرير سجل الخريجين (الملفات)",
    description:
      "بند §5-3 من عائلة الخريجين: سجل الخريجين وملفاتهم الرسمية — بطاقة الملف موجودة (GraduateFileCard) بلا تقرير ولا route.",
    beneficiaries: ["alumni_quality", "operational_units_staff", "dean", "vp_academic_affairs"],
    required_role: ["pending:g4_authorization_package"],
    data_scope: "university",
    source: "لا مصدر تقرير — مكونات عرض: src/components/graduates-affairs/GraduateFileCard.tsx (PR #186، بلا route)",
    filters: ["program_id", "graduation_year"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: ["tests/graduates-affairs/"],
    dependencies: ["src/components/graduates-affairs/GraduateFileCard.tsx"],
    status: "NOT_ACTIVATED",
    blocker: "لا تقرير سجل منشأ + مسودة SQL غير مطبقة + لا route + تفويض G4 معلق",
    evidence: ["docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "ALU-GRADUATION-DECISIONS",
    name_ar: "تقرير قرارات التخرج الرسمية",
    description:
      "بند §5-4 من عائلة الخريجين: قرارات التخرج الرسمية الموثقة (شرط إنشاء سجل خريج — fail-closed) — لا تقرير مجمع على main.",
    beneficiaries: ["dean", "vp_academic_affairs", "academic_affairs", "university_presidency_council"],
    required_role: ["pending:g4_authorization_package"],
    data_scope: "university/college",
    source: "لا مصدر تقرير — قرار التخرج الرسمي موثق كشرط داخل عقود PR #186 فقط",
    filters: ["college_id", "semester_id"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md"],
    status: "NOT_ACTIVATED",
    blocker: "لا تقرير قرارات منشأ + مسودة SQL غير مطبقة + تفويض G4 معلق",
    evidence: ["docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "ALU-COMMUNICATIONS-LOG",
    name_ar: "تقرير التواصل مع الخريجين",
    description:
      "بند §5-5 من عائلة الخريجين: سجل الاتصالات الموجهة للخريجين — لوحة العرض موجودة (GraduateCommunicationPanel) مع اختبارات، بلا route وبلا قوالب رسائل معتمدة.",
    beneficiaries: ["alumni_quality", "operational_units_staff", "vp_student_affairs"],
    required_role: ["pending:g4_authorization_package"],
    data_scope: "university",
    source: "عقود communications في src/lib/graduates-affairs/ + src/components/graduates-affairs/GraduateCommunicationPanel.tsx",
    filters: ["channel", "cohort", "date_range"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/graduates-affairs/"],
    dependencies: ["src/components/graduates-affairs/GraduateCommunicationPanel.tsx"],
    status: "UNDER_DEVELOPMENT",
    blocker: "لا route + قوالب الرسائل (قرار محتوى) معلقة + تفويض G4 معلق",
    evidence: [
      "src/components/graduates-affairs/GraduateCommunicationPanel.tsx",
      "docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md",
    ],
  },
  {
    report_code: "ALU-CONSENT-COMPLIANCE",
    name_ar: "تقرير موافقات الخريجين (الامتثال)",
    description:
      "بند §5-7 من عائلة الخريجين: حالة الموافقات المربوطة بالاستبيانات والتواصل — لا تقرير امتثال منشأ.",
    beneficiaries: ["alumni_quality", "dean", "university_presidency_council"],
    required_role: ["pending:g4_authorization_package"],
    data_scope: "university",
    source: "لا مصدر تقرير — عقود consents في src/lib/graduates-affairs/ فقط",
    filters: ["consent_type", "cohort"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduates-affairs/surveys.ts"],
    status: "NOT_ACTIVATED",
    blocker: "لا تقرير امتثال موافقات منشأ + تفويض G4 معلق",
    evidence: ["docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "ALU-CANDIDATES-PIPELINE",
    name_ar: "تقرير خط مرشحي التخرج",
    description:
      "بند §5-8 من عائلة الخريجين: متابعة مرشحي التخرج عبر مراحل الاعتماد — الميزة التشغيلية Live (route admin/graduation-candidates) والبيانات جاهزة، لكن لا تقرير مجمع منشأ.",
    beneficiaries: ["dean", "vp_academic_affairs", "academic_affairs", "operational_units_staff"],
    required_role: ["pending:graduates_report_roles (الصلاحية التشغيلية للمسار الحالي إدارية)"],
    data_scope: "university/college",
    source:
      "مصدر تشغيلي Live: src/routes/admin/graduation-candidates.tsx + عدّ «مرشحو تخرج معلقون» في لوحة القيادة (src/lib/executive-dashboard.functions.ts) — لا تقرير مجمع",
    filters: ["college_id", "status"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/routes/admin/graduation-candidates.tsx"],
    status: "SOURCE_READY",
    blocker: "المصدر التشغيلي Live لكن التقرير المجمع غير منشأ + تفويض G4 معلق",
    evidence: [
      "src/routes/admin/graduation-candidates.tsx",
      "src/lib/executive-dashboard.functions.ts (مرشحو تخرج معلقون)",
    ],
  },
  {
    report_code: "ALU-SURVEY-RESPONSE-RATE",
    name_ar: "تقرير معدلات الاستجابة لاستبيانات الخريجين",
    description:
      "بند فرعي من عائلة الخريجين: نسب الاستجابة للاستبيانات حسب الفوج/البرنامج — لا مصدر مخصص؛ مشتق مخطط من عقود الاستبيانات بعد تفعيلها.",
    beneficiaries: ["alumni_quality", "dean", "vp_academic_affairs"],
    required_role: ["pending:g4_authorization_package"],
    data_scope: "university/program cohorts",
    source: "لا مصدر تقرير مخصص على main — مشتق مخطط من src/lib/graduates-affairs/surveys.ts",
    filters: ["survey_id", "cohort"],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduates-affairs/surveys.ts"],
    status: "NOT_ACTIVATED",
    blocker: "يعتمد على تفعيل الاستبيانات (BLOCKED) + تفويض G4 معلق",
    evidence: ["docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "ALU-QUALITY-INDICATORS",
    name_ar: "مؤشرات جودة مخرجات الخريجين",
    description:
      "بند §5-9 من عائلة الخريجين: مؤشرات مجمعة لجودة المخرجات (توظيف/رضا/استجابة) لجهة الجودة — لا مصدر على main.",
    beneficiaries: ["alumni_quality", "university_presidency_council", "vp_academic_affairs"],
    required_role: ["pending:g4_authorization_package"],
    data_scope: "university",
    source: "لا مصدر تقرير على main — مركّب مخطط من تقارير الأفواج والاستبيانات بعد تفعيلها",
    filters: ["graduation_year", "program_id"],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/graduates-affairs/reports.ts", "src/lib/graduates-affairs/surveys.ts"],
    status: "NOT_ACTIVATED",
    blocker: "يعتمد على تقارير BLOCKED (أفواج/استبيانات) + تفويض G4 معلق",
    evidence: ["docs/GRADUATES-AFFAIRS-COMPLETION-01-REPORT.md"],
  },
  // ------------------------------------------------------------------
  // Lecture execution family — §5 items 1..6
  // ------------------------------------------------------------------
  {
    report_code: "LEC-EXECUTION-MONITORING",
    name_ar: "تقرير متابعة تنفيذ المحاضرات",
    description:
      "بندا §5-1 و§5-4 من عائلة متابعة المحاضرات (مدمجان): نسب التنفيذ/التعذر/التعويض بالقسم/المستوى/المقرر لرئيس القسم والعميد؛ أسابيع مرقمة وحالات ثمانٍ مغلقة؛ تأكيد مندوب D-15 configurable (افتراضي معطل).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["assignment:lecture_monitor (recorder/delegate/monitor — dean مقيد بقسم واحد)"],
    data_scope: "department/level/course",
    source:
      "VIEW (DRAFT-ONLY): lecture_execution_reporting (security_invoker) + src/lib/lecture-execution/domain.ts",
    filters: ["department_id", "level_id", "course_id", "week_no"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/lecture-execution/ (25 اختباراً)"],
    dependencies: [
      "src/components/lecture-execution/ExecutionMonitoringReport.tsx",
      "docs/drafts/20260722120000_lecture_execution_mvp_01.draft.sql",
    ],
    status: "BLOCKED",
    blocker: "مسودة SQL غير مطبقة + لا route + إدارة تعيينات recorders/delegates/monitors غير منشأة + قرار D-15 معلق",
    evidence: [
      "src/lib/lecture-execution/domain.ts",
      "src/components/lecture-execution/ExecutionMonitoringReport.tsx",
      "docs/LECTURE-EXECUTION-MVP-01-REPORT.md",
    ],
  },
  {
    report_code: "LEC-BY-FACULTY",
    name_ar: "تقرير تنفيذ المحاضرات حسب عضو هيئة التدريس",
    description:
      "بند §5-2 من عائلة متابعة المحاضرات: نسب التنفيذ لكل عضو هيئة تدريس — لا عرض مخصص (عرض المراقبة بالقسم/المستوى/المقرر فقط).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs"],
    required_role: ["assignment:lecture_monitor"],
    data_scope: "department",
    source: "لا مصدر تقرير مخصص على main — بُعد عضو هيئة التدريس غير موجود في عرض lecture_execution_reporting (DRAFT-ONLY)",
    filters: ["faculty_id", "semester_id"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/drafts/20260722120000_lecture_execution_mvp_01.draft.sql"],
    status: "NOT_ACTIVATED",
    blocker: "لا بُعد faculty في عرض التقرير المسودة + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/LECTURE-EXECUTION-MVP-01-REPORT.md"],
  },
  {
    report_code: "LEC-WEEKLY-LOG",
    name_ar: "سجل التنفيذ الأسبوعي للمحاضرات",
    description:
      "بند §5-3 من عائلة متابعة المحاضرات: سجل الجلسات الأسبوعي لعضو هيئة التدريس — بطاقة السجل موجودة (FacultyExecutionLogCard) مع اختبارات، بلا route وبلا SQL مطبق.",
    beneficiaries: ["faculty_supervisor", "dept_head_coordinator", "dean"],
    required_role: ["assignment:lecture_recorder"],
    data_scope: "course_section",
    source:
      "نموذج المجال في src/lib/lecture-execution/domain.ts + src/components/lecture-execution/FacultyExecutionLogCard.tsx (SQL DRAFT-ONLY)",
    filters: ["week_no", "section_id"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/lecture-execution/"],
    dependencies: [
      "src/components/lecture-execution/FacultyExecutionLogCard.tsx",
      "docs/drafts/20260722120000_lecture_execution_mvp_01.draft.sql",
    ],
    status: "UNDER_DEVELOPMENT",
    blocker: "مسودة SQL غير مطبقة + لا route + إدارة التعيينات غير منشأة",
    evidence: [
      "src/components/lecture-execution/FacultyExecutionLogCard.tsx",
      "docs/LECTURE-EXECUTION-MVP-01-REPORT.md",
    ],
  },
  {
    report_code: "LEC-DELEGATE-CONFIRMATIONS",
    name_ar: "تقرير تأكيدات المندوبين",
    description:
      "بند §5-5 من عائلة متابعة المحاضرات: حالة تأكيدات مندوبي المستويات (D-15 configurable، افتراضي معطل) — بطاقة التأكيد موجودة (DelegateConfirmationCard) بلا route.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs"],
    required_role: ["assignment:lecture_delegate"],
    data_scope: "level/department",
    source:
      "نموذج المجال في src/lib/lecture-execution/domain.ts + src/components/lecture-execution/DelegateConfirmationCard.tsx (SQL DRAFT-ONLY)",
    filters: ["level_id", "week_no", "confirmation_status"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: null,
    tests: ["tests/lecture-execution/"],
    dependencies: [
      "src/components/lecture-execution/DelegateConfirmationCard.tsx",
      "docs/drafts/20260722120000_lecture_execution_mvp_01.draft.sql",
    ],
    status: "UNDER_DEVELOPMENT",
    blocker: "قرار D-15 معلق + مسودة SQL غير مطبقة + لا route",
    evidence: [
      "src/components/lecture-execution/DelegateConfirmationCard.tsx",
      "docs/LECTURE-EXECUTION-MVP-01-REPORT.md",
    ],
  },
  {
    report_code: "LEC-EXCUSED-MAKEUP",
    name_ar: "تقرير المحاضرات المتعذرة والمعوضة (تفصيلي)",
    description:
      "بند فرعي من عائلة متابعة المحاضرات: سجل تفصيلي بالمحاضرات المتعذرة ومواعيد تعويضها — النسب مجمعة في تقرير المراقبة، لكن لا سجل تفصيلي منشأ.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs"],
    required_role: ["assignment:lecture_monitor"],
    data_scope: "department/course",
    source: "لا مصدر تقرير مخصص على main — الحالات مغلقة في src/lib/lecture-execution/domain.ts (SQL DRAFT-ONLY)",
    filters: ["department_id", "status", "week_no"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/drafts/20260722120000_lecture_execution_mvp_01.draft.sql"],
    status: "NOT_ACTIVATED",
    blocker: "لا سجل تفصيلي منشأ + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/LECTURE-EXECUTION-MVP-01-REPORT.md"],
  },
  {
    report_code: "LEC-PLAN-COVERAGE",
    name_ar: "تقرير تغطية الخطة/المنهاج بالمحاضرات",
    description:
      "بند §5-6 من عائلة متابعة المحاضرات: نسبة تغطية موضوعات الخطة المنفذة فعلياً — لا مصدر على main إطلاقاً.",
    beneficiaries: ["dept_head_coordinator", "vp_academic_affairs", "dean", "faculty_supervisor"],
    required_role: ["assignment:lecture_monitor"],
    data_scope: "course/department",
    source: "لا مصدر تقرير على main — يتطلب ربط موضوعات الخطة بسجلات التنفيذ (غير منشأ)",
    filters: ["course_id", "semester_id"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/drafts/20260722120000_lecture_execution_mvp_01.draft.sql"],
    status: "NOT_ACTIVATED",
    blocker: "نموذج تغطية المنهاج غير منشأ + مسودة SQL غير مطبقة + لا route",
    evidence: ["docs/LECTURE-EXECUTION-MVP-01-REPORT.md"],
  },
  // ------------------------------------------------------------------
  // Learning materials family — §5 items 1..6 (feature Live, no reports)
  // ------------------------------------------------------------------
  {
    report_code: "MAT-USAGE-REPORT",
    name_ar: "تقرير استخدام المواد التعليمية",
    description:
      "بند §5-1 من عائلة المواد التعليمية: تقرير مجمع عن استخدام المواد (عرض/تحميل) — غير منشأ؛ الميزة نفسها Live (رفع وإدارة للعضو وعرض للطالب) والجداول جاهزة.",
    beneficiaries: ["faculty_supervisor", "dept_head_coordinator", "dean", "vp_academic_affairs", "student"],
    required_role: ["pending:materials_report_roles"],
    data_scope: "course/department",
    source:
      "مصدر الميزة Live: src/routes/faculty-portal.materials.tsx + src/routes/student.materials.tsx — لا باني/دالة تقرير",
    filters: ["course_id", "material_type"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
    status: "SOURCE_READY",
    blocker: "الجداول/الميزة Live لكن لم يُنشأ أي تقرير/باني/دالة لاستخدام المواد",
    evidence: [
      "src/routes/faculty-portal.materials.tsx",
      "src/routes/student.materials.tsx",
      "docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md",
    ],
  },
  {
    report_code: "MAT-COURSE-COVERAGE",
    name_ar: "تقرير تغطية المقررات بالمواد التعليمية",
    description:
      "بند §5-2 من عائلة المواد التعليمية: أي المقررات/الشعب لديها مواد منشورة وأيها بلا مواد — غير منشأ؛ الجداول جاهزة.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "academic_affairs"],
    required_role: ["pending:materials_report_roles"],
    data_scope: "department/college",
    source: "لا مصدر تقرير — جداول المواد Live عبر src/routes/faculty-portal.materials.tsx",
    filters: ["department_id", "semester_id"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
    status: "SOURCE_READY",
    blocker: "لا تقرير تغطية منشأ رغم جاهزية الجداول",
    evidence: ["src/routes/faculty-portal.materials.tsx"],
  },
  {
    report_code: "MAT-PUBLISH-STATUS",
    name_ar: "تقرير حالة نشر المواد (منشورة/مسودة)",
    description:
      "بند §5-3 من عائلة المواد التعليمية: عدّ المواد بحالة النشر لكل مقرر/قسم — غير منشأ؛ الجداول جاهزة.",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["pending:materials_report_roles"],
    data_scope: "course/department",
    source: "لا مصدر تقرير — جداول المواد Live عبر src/routes/faculty-portal.materials.tsx",
    filters: ["publish_status", "course_id"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
    status: "SOURCE_READY",
    blocker: "لا تقرير حالة نشر منشأ رغم جاهزية الجداول",
    evidence: ["src/routes/faculty-portal.materials.tsx"],
  },
  {
    report_code: "MAT-TOP-ACCESSED",
    name_ar: "تقرير أكثر المواد وصولاً/تحميلاً",
    description:
      "بند §5-4 من عائلة المواد التعليمية: ترتيب المواد الأكثر استخداماً — يتطلب تتبع أحداث وصول غير مؤكد على main.",
    beneficiaries: ["faculty_supervisor", "dept_head_coordinator", "dean", "vp_academic_affairs"],
    required_role: ["pending:materials_report_roles"],
    data_scope: "course/department",
    source: "لا مصدر تقرير — لا تتبع أحداث وصول/تحميل مثبت على main",
    filters: ["course_id", "period"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
    status: "NOT_ACTIVATED",
    blocker: "لا عدّادات/أحداث استخدام مثبتة + لا تقرير منشأ",
    evidence: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
  },
  {
    report_code: "MAT-STALE-ITEMS",
    name_ar: "تقرير المواد غير المحدثة",
    description:
      "بند §5-5 من عائلة المواد التعليمية: مواد لم تُحدَّث منذ مدة (مؤشر جودة محتوى) — غير منشأ؛ الجداول جاهزة (طوابع زمنية).",
    beneficiaries: ["dept_head_coordinator", "dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["pending:materials_report_roles"],
    data_scope: "course/department",
    source: "لا مصدر تقرير — جداول المواد Live عبر src/routes/faculty-portal.materials.tsx",
    filters: ["stale_threshold_days", "department_id"],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
    status: "SOURCE_READY",
    blocker: "لا تقرير مواد قديمة منشأ رغم جاهزية الجداول",
    evidence: ["src/routes/faculty-portal.materials.tsx"],
  },
  {
    report_code: "MAT-STUDENT-ENGAGEMENT",
    name_ar: "تقرير تفاعل الطلاب مع المواد",
    description:
      "بند §5-6 من عائلة المواد التعليمية: مؤشرات وصول/تفاعل الطلاب مع مواد مقرراتهم — يتطلب تتبع أحداث غير مثبت على main.",
    beneficiaries: ["faculty_supervisor", "dept_head_coordinator", "dean", "vp_academic_affairs"],
    required_role: ["pending:materials_report_roles"],
    data_scope: "course/department",
    source: "لا مصدر تقرير — لا تتبع تفاعل طلابي مثبت على main",
    filters: ["course_id", "level_id"],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
    status: "NOT_ACTIVATED",
    blocker: "لا تتبع تفاعل مثبت + لا تقرير منشأ",
    evidence: ["docs/LEARNING-MATERIALS-ACTIVATION-01-REPORT.md"],
  },
  // ------------------------------------------------------------------
  // Student requests & documents family — remaining §5 items
  // ------------------------------------------------------------------
  {
    report_code: "REQ-PROCESSING-TIME",
    name_ar: "تقرير متوسط زمن معالجة الطلبات",
    description:
      "بند §5-5 من عائلة الطلبات والوثائق: متوسط زمن المعالجة حسب نوع الطلب/الوحدة — جدول student_requests Live (طوابع زمنية) لكن لا باني مخصص؛ جدول pending_age في الباني المجمع جزئية أقرب.",
    beneficiaries: ["vp_student_affairs", "operational_units_staff", "dean", "university_presidency_council"],
    required_role: ["pending:requests_report_roles (مرجح REPORTS_ROLES)"],
    data_scope: "university",
    source: "لا مصدر تقرير مخصص — table: student_requests Live + جزئية pending_age في src/lib/reports/request-reports.ts",
    filters: ["request_type", "unit", "period"],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/reports/request-reports.ts"],
    status: "SOURCE_READY",
    blocker: "الجدول Live لكن لا باني/عرض زمن معالجة منشأ",
    evidence: ["src/lib/reports/request-reports.ts (pending_age)", "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md"],
  },
  {
    report_code: "REQ-OVERDUE-SLA",
    name_ar: "تقرير الطلبات المتجاوزة لمدة الخدمة (SLA)",
    description:
      "بند §5-6 من عائلة الطلبات والوثائق: الطلبات المتجاوزة لعتبات زمنية معتمدة — العتبات غير معرفة؛ جزئية pending_age الأقرب.",
    beneficiaries: ["vp_student_affairs", "operational_units_staff", "dean"],
    required_role: ["pending:requests_report_roles (مرجح REPORTS_ROLES)"],
    data_scope: "university",
    source: "لا مصدر تقرير مخصص — table: student_requests Live؛ عتبات SLA غير معرفة على main",
    filters: ["sla_threshold", "request_type"],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/reports/request-reports.ts"],
    status: "SOURCE_READY",
    blocker: "عتبات SLA غير معتمدة + لا تقرير منشأ",
    evidence: ["src/lib/reports/request-reports.ts (pending_age)"],
  },
  {
    report_code: "REQ-DOCUMENTS-ISSUED",
    name_ar: "تقرير الوثائق الصادرة بالفترة والنوع",
    description:
      "بند §5-3 من عائلة الطلبات والوثائق: عدّ الوثائق الرسمية الصادرة بالفترة/النوع — جدول official_documents Live (يُعدّ في لوحة القيادة) والمسارات التشغيلية Live، لكن لا تقرير منشأ.",
    beneficiaries: ["vp_student_affairs", "operational_units_staff", "dean"],
    required_role: ["pending:requests_report_roles (مرجح REPORTS_ROLES)"],
    data_scope: "university",
    source:
      "لا مصدر تقرير مخصص — table: official_documents Live (وثائق اليوم في src/lib/executive-dashboard.functions.ts) + src/routes/admin/documents.lazy.tsx",
    filters: ["document_type", "period"],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/routes/admin/documents.lazy.tsx"],
    status: "SOURCE_READY",
    blocker: "الجدول Live لكن لا تقرير وثائق صادرة منشأ",
    evidence: ["src/lib/executive-dashboard.functions.ts (وثائق اليوم)", "src/routes/admin/documents.lazy.tsx"],
  },
  {
    report_code: "REQ-DOCUMENTS-SERVICES",
    name_ar: "تقرير الوثائق والخدمات المجمع",
    description:
      "بند §5-7 من عائلة الطلبات والوثائق: تقرير مجمع لإصدار الوثائق والخدمات — قسم «الوثائق» في صفحة التقارير = «سيتم تفعيل هذا القسم لاحقاً» ومسجّل gap.",
    beneficiaries: ["vp_student_affairs", "operational_units_staff", "dean"],
    required_role: ["pending:requests_report_roles (مرجح REPORTS_ROLES)"],
    data_scope: "university",
    source:
      "لا مصدر تقرير — مصادر تشغيلية فقط: src/routes/admin/documents.lazy.tsx + src/routes/mobile.student.documents.* + table: official_documents",
    filters: [],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: ["tests/documents/ (للميزة التشغيلية، لا للتقرير)"],
    dependencies: ["src/lib/reports/report-catalog.ts (documents_services_report gap)"],
    status: "NOT_ACTIVATED",
    blocker: "قسم «سيتم تفعيل هذا القسم لاحقاً» في src/routes/admin/reports.tsx؛ مسجّل gap في report-catalog (أولوية منخفضة)",
    evidence: ["src/routes/admin/reports.tsx (قسم documents: سيتم تفعيل هذا القسم لاحقاً)", "src/lib/reports/report-catalog.ts"],
  },
  // ------------------------------------------------------------------
  // Documented governance / audit gaps
  // ------------------------------------------------------------------
  {
    report_code: "AUD-SECURITY-REPORT",
    name_ar: "تقرير التدقيق والأمان المجمع",
    description:
      "قسم «التدقيق والأمان» في صفحة التقارير = «سيتم تفعيل هذا القسم لاحقاً»؛ البنية التحتية موجودة (audit_logs + RLS scoped + log_audit RPC) بلا تقرير مجمع.",
    beneficiaries: ["university_presidency_council", "dean"],
    required_role: ["admin", "system_admin"],
    data_scope: "university",
    source: "لا مصدر تقرير — بنية تحتية: table audit_logs + src/lib/authz.server.ts (AUDIT_LOG_* roles) + rpc:log_audit",
    filters: [],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/authz.server.ts"],
    status: "NOT_ACTIVATED",
    blocker: "مسجّل gap في report-catalog (audit_security_report، أولوية عالية)؛ يحتاج عقداً مجمعاً",
    evidence: ["src/lib/reports/report-catalog.ts", "src/routes/admin/reports.tsx (قسم audit: سيتم تفعيل هذا القسم لاحقاً)"],
  },
  {
    report_code: "AUD-ROLE-CHANGES",
    name_ar: "تقرير تغييرات الأدوار",
    description: "تتبع تغييرات أدوار المستخدمين — فجوة موثقة متوسطة الأولوية.",
    beneficiaries: ["university_presidency_council"],
    required_role: ["admin", "system_admin"],
    data_scope: "university",
    source: "لا مصدر تقرير على main",
    filters: [],
    sensitivity: "restricted",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/reports/report-catalog.ts (role_changes_report gap)"],
    status: "NOT_ACTIVATED",
    blocker: "مسجّل gap في report-catalog (role_changes_report)",
    evidence: ["src/lib/reports/report-catalog.ts"],
  },
  {
    report_code: "DEPT-ACADEMIC-LOAD",
    name_ar: "لوحة رئيس القسم (العبء الأكاديمي والجداول)",
    description:
      "عرض مجمع بصلاحية رئيس قسم للعبء الأكاديمي — البيانات حالياً حبيسة صلاحية الإدارة العامة؛ تقارير الجداول (SCHEDULE_REPORT_ROLES) هي الوحيدة التي تمنحه وصولاً جزئياً.",
    beneficiaries: ["dept_head_coordinator"],
    required_role: ["department_head"],
    data_scope: "department",
    source: "لا مصدر تقرير مخصص — أقرب مغطاة جزئية: تقارير الجداول في /admin/reports (ADM-SCHEDULE-SUITE)",
    filters: [],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/reports/report-catalog.ts (department_academic_load gap)"],
    status: "NOT_ACTIVATED",
    blocker: "مسجّل gap في report-catalog (department_academic_load، أولوية عالية)",
    evidence: ["src/lib/reports/report-catalog.ts", "docs/PORTAL-REPORTING-COVERAGE-AUDIT-01-REPORT.md"],
  },
  {
    report_code: "FAC-TEACHING-LOAD",
    name_ar: "تقرير العبء التدريسي المجمع لأعضاء هيئة التدريس",
    description:
      "قسم «أعضاء هيئة التدريس» في صفحة التقارير = «سيتم تفعيل هذا القسم لاحقاً»؛ يوجد جزئياً تقرير عبء ضمن جناح الجداول (بصلاحية إدارية).",
    beneficiaries: ["dean", "vp_academic_affairs", "faculty_supervisor"],
    required_role: ["pending:faculty_report_roles (مرجح REPORTS_ROLES)"],
    data_scope: "university/college",
    source: "لا مصدر تقرير مستقل — جزئية: getFacultyLoadReportForAdmin ضمن جناح الجداول في src/lib/admin-reports.functions.ts",
    filters: [],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/reports/report-catalog.ts (faculty_teaching_load gap)"],
    status: "NOT_ACTIVATED",
    blocker: "قسم «سيتم تفعيل هذا القسم لاحقاً» + مسجّل gap في report-catalog (faculty_teaching_load، أولوية متوسطة)",
    evidence: ["src/routes/admin/reports.tsx (قسم faculty: سيتم تفعيل هذا القسم لاحقاً)", "src/lib/reports/report-catalog.ts"],
  },
  {
    report_code: "PER-PERSON-STAFF-PERFORMANCE",
    name_ar: "أداء الموظفين على مستوى الفرد",
    description:
      "تقرير أداء فردي للموظفين — مُستبعد تصميمياً (تعريف شخصي)؛ البديل المعتمد: نشاط المعالجة حسب الدور الوظيفي (AGG-STAFF-ACTIVITY-BY-ROLE).",
    beneficiaries: ["university_presidency_council"],
    required_role: ["pending:governance_decision (يتطلب قرار حوكمة صريحاً قبل أي تنفيذ)"],
    data_scope: "university",
    source: "لا مصدر — مستبعد تصميمياً",
    filters: [],
    sensitivity: "personal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/reports/staff-activity-reports.ts (البديل المعتمد على مستوى الدور)"],
    status: "BLOCKED",
    blocker: "قرار حوكمة غائب — مُستبعد تصميمياً ومسجّل gap في report-catalog (per_person_staff_performance)",
    evidence: ["src/lib/reports/report-catalog.ts", "docs/REPORTS-AND-DASHBOARDS-COMPLETION-01-REPORT.md §5.6"],
  },
  // ------------------------------------------------------------------
  // Student self-service (the single proven LIVE entry) + legacy orphans
  // ------------------------------------------------------------------
  {
    report_code: "STU-SELF-SERVICE-VIEWS",
    name_ar: "عروض الطالب الذاتية (طلباتي/موادي/جدولي/تقدمي/وثائقي)",
    description:
      "بيانات شخصية self-service عبر بوابة الطالب والجوال — ليست تقارير مجمعة لكنها تغطي بند §5 «تتبع الطالب لطلباته ووثائقه» واحتياج المستفيد «طالب». LIVE الوحيد المثبت: مصدر + صلاحية (self-scoped RLS) + routes + اختبارات + ربط فعلي.",
    beneficiaries: ["student"],
    required_role: ["student"],
    data_scope: "self",
    source:
      "src/routes/student.requests.tsx + src/routes/student.materials.* + src/routes/mobile.student.* (requests/documents/finance/grades/schedule/academic-record)",
    filters: [],
    sensitivity: "personal",
    output_types: ["screen"],
    route: "/student/requests",
    tests: ["tests/student-requests/", "tests/student-portal/"],
    dependencies: ["src/lib/reports/report-catalog.ts (existing)"],
    status: "LIVE",
    blocker: null,
    evidence: [
      "src/routes/student.requests.tsx",
      "tests/student-requests/",
      "src/lib/reports/report-catalog.ts (existing)",
    ],
  },
  {
    report_code: "LEGACY-ORPHAN-HANDLERS",
    name_ar: "دوال التقارير القديمة اليتيمة (أكاديمي/أداء/قبول/هيئة تدريس/مالي)",
    description:
      "خمس دوال reportsHandler موجودة في admin-reports.functions.ts بلا أي مستهلك في الواجهة — مرشحة للإزالة أو الاستبدال بعقود PR #192 المجمعة.",
    beneficiaries: ["dean", "vp_academic_affairs"],
    required_role: ["system_admin", "admin", "dean", "registrar", "finance_officer", "student_affairs"],
    data_scope: "university",
    source:
      "getReportsAcademic/getReportsPerformance/getReportsEnrollment/getReportsFaculty/getReportsFinancial في src/lib/admin-reports.functions.ts",
    filters: [],
    sensitivity: "internal",
    output_types: [],
    route: null,
    tests: [],
    dependencies: ["src/lib/reports/finance-reports.ts (بديل المالية المجمع)"],
    status: "NOT_ACTIVATED",
    blocker: "غير موصولة بأي route — يستورد reports.tsx من العائلة القديمة getReportsRequests فقط",
    evidence: ["src/lib/admin-reports.functions.ts", "src/routes/admin/reports.tsx (قائمة الاستيرادات)"],
  },
  // ------------------------------------------------------------------
  // Academic councils reports (C9)
  // ------------------------------------------------------------------
  {
    report_code: "COUNCIL-MEETINGS-BY-PERIOD",
    name_ar: "تقرير اجتماعات المجلس حسب الفترة",
    description:
      "قائمة باجتماعات المجلس الأكاديمي ضمن فترة زمنية محددة، مع الحالة والموعد والمكان.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_meetings_by_period في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: ["from", "to"],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-ATTENDANCE-RATE",
    name_ar: "تقرير معدل حضور المجلس",
    description:
      "معدل الحضور والغياب لأعضاء المجلس بناءً على سجلات الحضور المُعتمدة.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_attendance_rate في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-QUORUM-HISTORY",
    name_ar: "تقرير تاريخ نصاب المجلس",
    description:
      "سجل تقييمات النصاب القانوني للاجتماعات مع عدد الحاضرين والنصاب المطلوب.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_quorum_history في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-TOPIC-DISPOSITION",
    name_ar: "تقرير توزيع حالات موضوعات المجلس",
    description:
      "توزيع الموضوعات المقدمة على حالاتها (مسودة، مقدم، قيد المراجعة، مقبول، مرفوض...).",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_topic_disposition في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-AGENDA-COMPLETION",
    name_ar: "تقرير إنجاز جدول أعمال المجلس",
    description:
      "عدد بنود جدول الأعمال لكل اجتماع وما تم اعتماده ومُبت فيه.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_agenda_completion في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-VOTE-RESULT-SUMMARY",
    name_ar: "تقرير ملخص نتائج تصويت المجلس",
    description:
      "نتائج التصويت على بنود جدول الأعمال: موافق، رافض، محايد، والنتيجة.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_vote_result_summary في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-DECISION-EXECUTION-STATUS",
    name_ar: "تقرير حالة تنفيذ قرارات المجلس",
    description:
      "حالة تنفيذ القرارات الصادرة: صادر، قيد التنفيذ، مكتمل، معطل، متأخر.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_decision_execution_status في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-OVERDUE-DECISIONS",
    name_ar: "تقرير قرارات المجلس المتأخرة",
    description:
      "القرارات التي تجاوزت موعد الاستحقاق ولم تُعلَن مكتملة بعد.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_overdue_decisions في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-MEETING-DURATION",
    name_ar: "تقرير مدة اجتماعات المجلس",
    description:
      "مدة كل اجتماع محسوبة من فتح الجلسة حتى إغلاقها.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_meeting_duration في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-ARCHIVE-STATUS",
    name_ar: "تقرير حالة أرشفة المجلس",
    description:
      "إحصائية باجتماعات المجلس المؤرشفة والملغاة والنشطة.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_archive_status في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
  {
    report_code: "COUNCIL-ACTIVITY",
    name_ar: "تقرير نشاط المجلس",
    description:
      "مؤشرات مجمعة عن نشاط المجلس: أعضاء، اجتماعات، موضوعات، قرارات، أصوات، آخر حدث.",
    beneficiaries: ["academic_affairs", "dean"],
    required_role: ["chair", "secretary", "member"],
    data_scope: "council",
    source:
      "RPC get_council_report_council_activity في supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
    filters: [],
    sensitivity: "internal",
    output_types: ["screen"],
    route: "/faculty-portal/academic-councils/reports",
    tests: ["tests/academic-councils/postgres-c9-notifications-reporting-verifier.sql"],
    dependencies: [
      "src/lib/councils-c9.functions.ts",
      "src/components/councils/CouncilReportsView.tsx",
    ],
    status: "LIVE",
    blocker: null,
    evidence: [
      "supabase/migrations/20260808180000_councils_c9_notifications_reporting_01.sql",
      "src/components/councils/CouncilReportsView.tsx",
    ],
  },
];
