-- STAFF-PORTAL-REVIEW-REMEDIATION-01
-- DRAFT ONLY — DO NOT APPLY FROM THIS PATH.
-- Source: staff-portal code review 2026-10-01.
-- Generated by copying each function's LATEST migration definition verbatim
-- and replacing only the commented fragments (CREATE OR REPLACE keeps
-- existing grants). Applied migrations are intentionally not edited.
-- Every section needs PG17 harness tests (allow + deny per role) before apply.

BEGIN;

-- 1) B1 staff could never RETURN or REJECT a request.
--    The executor fully implements return/reject (comment required, transition
--    resolution, request status), but the literal check
--    `p_action IS DISTINCT FROM v_config.action_type` rejected them with
--    B1_ACTION_TYPE_MISMATCH, while the UI offers both buttons.
--    Fix: allow them only when request_type_workflow_steps.can_return_to_student
--    / can_reject is true. Authorization (direct assignee + exact processing
--    binding + predecessor checks) is unchanged and still runs first.

CREATE OR REPLACE FUNCTION public.act_on_b1_student_request_step_atomic(
  p_step_id uuid, p_action text, p_comment text DEFAULT NULL::text, p_payload jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid:=auth.uid(); v_step public.student_request_workflow_steps%ROWTYPE;
  v_config public.request_type_workflow_steps%ROWTYPE; v_transition public.request_type_workflow_transitions%ROWTYPE;
  v_result text; v_next_id uuid; v_transition_count integer; v_request_type text; v_canonical text;
  v_action text; v_transition_id uuid; v_next_order integer; v_skipped integer := 0;
  v_is_p1 boolean := false;  -- P1-07
BEGIN
  PERFORM set_config('b1.atomic_action','1',true);
  LOCK TABLE public.request_type_workflow_transitions IN SHARE MODE;
  IF v_uid IS NULL THEN RAISE EXCEPTION 'AUTHENTICATION_REQUIRED' USING ERRCODE='28000'; END IF;
  SELECT s.* INTO v_step FROM public.student_request_workflow_steps s WHERE s.id=p_step_id FOR UPDATE;
  IF NOT FOUND OR v_step.status IS DISTINCT FROM 'active' THEN RAISE EXCEPTION 'B1_ACTIVE_STEP_REQUIRED'; END IF;
  SELECT r.request_type INTO v_request_type FROM public.student_requests r WHERE r.id=v_step.student_request_id FOR UPDATE;
  v_canonical:=CASE v_request_type WHEN 'absence_excuse' THEN 'excused_absence' WHEN 'transfer' THEN 'department_transfer'
    WHEN 'extra_chance' THEN 'final_chance' ELSE v_request_type END;
  v_is_p1 := public.p1_is_atomic_submit_service(v_canonical);  -- P1-07
  IF v_canonical NOT IN ('enrollment_suspension','excused_absence','department_transfer','final_chance','file_withdrawal')
     AND NOT v_is_p1  -- P1-07: P1 services reuse this executor unchanged
    THEN RAISE EXCEPTION 'B1_REQUEST_REQUIRED'; END IF;
  SELECT c.* INTO v_config FROM public.request_type_workflow_steps c WHERE c.id=v_step.workflow_step_id FOR SHARE;
  v_action := p_action;
  IF NOT public.can_current_user_act_on_step(p_step_id, COALESCE(v_config.action_type,'')) THEN
    RAISE EXCEPTION 'B1_DIRECT_ASSIGNEE_AUTHORIZATION_REQUIRED' USING ERRCODE='42501'; END IF;
  IF EXISTS (SELECT 1 FROM public.student_request_workflow_steps prior
    WHERE prior.student_request_id=v_step.student_request_id AND prior.step_order<v_step.step_order
      AND prior.status NOT IN ('completed','skipped')) THEN RAISE EXCEPTION 'B1_PREDECESSOR_INCOMPLETE'; END IF;
  -- STAFF-PORTAL-REVIEW-REMEDIATION-01: 'return'/'reject' are exit actions
  -- gated by the step's own flags; every other action must still equal the
  -- configured action_type literally (no aliasing).
  IF v_config.action_type IS NULL THEN
    RAISE EXCEPTION 'B1_ACTION_TYPE_MISMATCH' USING ERRCODE='42501';
  END IF;
  IF p_action = 'return' THEN
    IF NOT COALESCE(v_config.can_return_to_student, false) THEN
      RAISE EXCEPTION 'B1_ACTION_NOT_ALLOWED_FOR_STEP' USING ERRCODE='42501';
    END IF;
  ELSIF p_action = 'reject' THEN
    IF NOT COALESCE(v_config.can_reject, false) THEN
      RAISE EXCEPTION 'B1_ACTION_NOT_ALLOWED_FOR_STEP' USING ERRCODE='42501';
    END IF;
  ELSIF p_action IS DISTINCT FROM v_config.action_type THEN
    RAISE EXCEPTION 'B1_ACTION_TYPE_MISMATCH' USING ERRCODE='42501';
  END IF;
  IF v_action IN ('confirm_payment','issue_document','sign') THEN RAISE EXCEPTION 'B1_SPECIALIZED_ACTION_RPC_REQUIRED'; END IF;

  IF v_is_p1 AND v_step.step_key IN ('card_issuance','registrar_apply_result') THEN
    RAISE EXCEPTION 'P1_SPECIALIZED_ACTION_RPC_REQUIRED' USING ERRCODE='42501';
  END IF;

  IF COALESCE(p_payload,'{}'::jsonb)<>'{}'::jsonb THEN RAISE EXCEPTION 'B1_CLIENT_ACTION_PAYLOAD_FORBIDDEN'; END IF;
  v_result:=CASE v_action WHEN 'review' THEN 'reviewed' WHEN 'approve' THEN 'approved'
    WHEN 'clear' THEN 'cleared' WHEN 'apply_decision' THEN 'applied' WHEN 'archive' THEN 'archived'
    WHEN 'reject' THEN 'reject' WHEN 'return' THEN 'return' ELSE NULL END;
  IF v_result IS NULL THEN RAISE EXCEPTION 'B1_ACTION_NOT_SUPPORTED'; END IF;
  IF v_action IN ('reject','return') AND COALESCE(btrim(p_comment),'')='' THEN RAISE EXCEPTION 'B1_COMMENT_REQUIRED'; END IF;

  v_transition_id := public.resolve_b1_workflow_transition(
    v_step.workflow_id, v_step.workflow_step_id, v_result, v_step.student_request_id);
  SELECT t.* INTO v_transition FROM public.request_type_workflow_transitions t WHERE t.id=v_transition_id FOR SHARE;

  IF v_transition.to_step_id IS NOT NULL THEN
    SELECT count(*),(array_agg(s.id ORDER BY s.id))[1],(array_agg(s.step_order ORDER BY s.id))[1]
      INTO v_transition_count,v_next_id,v_next_order
    FROM public.student_request_workflow_steps s WHERE s.student_request_id=v_step.student_request_id
      AND s.workflow_step_id=v_transition.to_step_id AND s.status='pending';
    IF v_transition_count<>1 THEN RAISE EXCEPTION 'B1_NEXT_RUNTIME_STEP_MUST_RESOLVE_ONCE:%',v_transition_count; END IF;
  END IF;
  UPDATE public.student_request_workflow_steps SET status=CASE v_action WHEN 'reject' THEN 'rejected'
    WHEN 'return' THEN 'returned' ELSE 'completed' END,decision=CASE v_action WHEN 'reject' THEN 'rejected'
    WHEN 'return' THEN 'returned' ELSE v_result END,comment=p_comment,completed_by=v_uid,completed_at=now(),updated_at=now()
    WHERE id=v_step.id;

  IF v_next_id IS NOT NULL AND v_next_order > v_step.step_order + 1 THEN
    WITH bypassed AS (
      SELECT s.id, COALESCE(c.requires_payment,false) AS requires_payment
      FROM public.student_request_workflow_steps s
      LEFT JOIN public.request_type_workflow_steps c ON c.id = s.workflow_step_id
      WHERE s.student_request_id = v_step.student_request_id
        AND s.status = 'pending'
        AND s.step_order > v_step.step_order
        AND s.step_order < v_next_order
    )
    UPDATE public.student_request_workflow_steps s
      SET status='skipped', decision='skipped', completed_at=now(), updated_at=now(),
          metadata = COALESCE(s.metadata,'{}'::jsonb) || jsonb_build_object(
            'skip_reason', CASE WHEN b.requires_payment THEN 'fee_not_required' ELSE 'branch_bypassed' END,
            'skipped_by_transition_id', v_transition_id)
      FROM bypassed b WHERE b.id = s.id;
    GET DIAGNOSTICS v_skipped = ROW_COUNT;
    IF v_skipped > 0 THEN
      INSERT INTO public.student_request_workflow_events(student_request_id,workflow_step_runtime_id,event_type,actor_user_id,
        actor_unit_id,actor_role_id,message_ar,payload,visible_to_student)
      VALUES(v_step.student_request_id,v_step.id,'skip',v_uid,v_step.processing_unit_id,v_step.processing_role_id,
        'تم تخطي خطوات غير مطلوبة وفق شروط سير العمل',
        jsonb_build_object('skipped_steps',v_skipped,'transition_id',v_transition_id),true);
    END IF;
  END IF;

  IF v_next_id IS NOT NULL AND v_action='apply_decision' AND v_canonical='file_withdrawal'
     AND EXISTS (SELECT 1 FROM public.student_request_workflow_steps next_step
       JOIN public.request_type_workflow_steps next_config ON next_config.id=next_step.workflow_step_id
       WHERE next_step.id=v_next_id AND next_config.step_key='archive') THEN
    PERFORM public.apply_b1_academic_effect_for_request(v_step.student_request_id);
  END IF;
  IF v_next_id IS NOT NULL THEN UPDATE public.student_request_workflow_steps SET status='active',entered_at=now(),updated_at=now()
    WHERE id=v_next_id AND status='pending'; END IF;
  IF (SELECT count(*) FROM public.student_request_workflow_steps s WHERE s.student_request_id=v_step.student_request_id AND s.status='active')
     <> (CASE WHEN v_next_id IS NULL THEN 0 ELSE 1 END) THEN RAISE EXCEPTION 'B1_ACTIVE_STEP_INVARIANT_FAILED'; END IF;
  INSERT INTO public.student_request_workflow_events(student_request_id,workflow_step_runtime_id,event_type,actor_user_id,
    actor_unit_id,actor_role_id,message_ar,payload,visible_to_student)
  VALUES(v_step.student_request_id,v_step.id,CASE v_action WHEN 'reject' THEN 'rejected' WHEN 'return' THEN 'returned'
    ELSE v_result END,v_uid,v_step.processing_unit_id,v_step.processing_role_id,p_comment,
    jsonb_build_object('action',v_action,'action_result',v_result,'transition_id',v_transition.id),true);
  IF v_next_id IS NULL THEN
    UPDATE public.student_requests SET status=CASE v_action WHEN 'reject' THEN 'rejected'
      WHEN 'return' THEN 'returned_for_completion' ELSE 'completed' END,updated_at=now(),completed_at=CASE
        WHEN v_action='return' THEN completed_at ELSE now() END WHERE id=v_step.student_request_id;
    -- P1-07: P1 services carry NO B1 academic effect on this path.
    IF v_action='apply_decision' AND NOT v_is_p1 THEN
      PERFORM public.apply_b1_academic_effect_for_request(v_step.student_request_id);
    END IF;
  ELSE
    UPDATE public.student_requests SET status='in_review',updated_at=now() WHERE id=v_step.student_request_id;
  END IF;
  RETURN jsonb_build_object('success',true,'step_id',v_step.id,'action_result',v_result,
    'next_step_id',v_next_id,'transition_applied',true,'skipped_steps',v_skipped);
END;
$function$;

-- 2) Staff self-service approvals: an admin could approve their OWN request
--    and every step of it (has_role returns true for any role when
--    staff_service_is_admin; the self-approval guard exempted admins).
--    Overtime/training/clearance/evaluation flows already deny this.
--    PRE-APPLY: confirm every step role (direct_manager, hr, finance,
--    administrator) has real staff_service_role_assignments rows, or pending
--    requests will stall.

create or replace function public.staff_service_decide_request(
  p_request_id uuid,
  p_decision text,
  p_reason text,
  p_idempotency_key uuid
)
returns public.staff_service_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_request public.staff_service_requests%rowtype;
  v_step public.staff_service_approval_steps%rowtype;
  v_owner_user_id uuid;
  v_next_step integer;
  v_actor_role text;
  v_target_status text;
begin
  if auth.uid() is null then
    raise exception 'STAFF_SERVICE_AUTH_REQUIRED' using errcode = '42501';
  end if;

  if p_decision not in ('approved', 'rejected') then
    raise exception 'STAFF_SERVICE_DECISION_INVALID' using errcode = '22023';
  end if;

  if p_idempotency_key is null then
    raise exception 'STAFF_SERVICE_IDEMPOTENCY_REQUIRED' using errcode = '22023';
  end if;

  if p_decision = 'rejected' and nullif(btrim(p_reason), '') is null then
    raise exception 'STAFF_SERVICE_REJECTION_REASON_REQUIRED' using errcode = '22023';
  end if;

  select r.*
    into v_request
  from public.staff_service_requests r
  where r.id = p_request_id
  for update of r;

  if not found then
    raise exception 'STAFF_SERVICE_REQUEST_NOT_FOUND' using errcode = 'P0002';
  end if;

  select sp.user_id into v_owner_user_id
  from public.staff_profiles sp
  where sp.id = v_request.staff_profile_id;

  if exists (
    select 1 from public.staff_service_events e
    where e.request_id = p_request_id
      and e.event_type = 'approval_decided'
      and e.correlation_id = p_idempotency_key
  ) then
    return v_request;
  end if;

  if v_request.status not in ('submitted', 'in_review') then
    raise exception 'STAFF_SERVICE_REQUEST_NOT_ACTIONABLE' using errcode = '55000';
  end if;

  select * into v_step
  from public.staff_service_approval_steps
  where request_id = p_request_id
    and step_order = v_request.current_step
  for update;

  if not found or v_step.status <> 'pending' then
    raise exception 'STAFF_SERVICE_PENDING_STEP_NOT_FOUND' using errcode = '55000';
  end if;

  v_actor_role := v_step.required_role;

  -- STAFF-PORTAL-REVIEW-REMEDIATION-01: no self-approval for anyone
  -- (admins included), and the approver must hold a REAL assignment for the
  -- step's role — the generic admin short-circuit in staff_service_has_role
  -- is not accepted for approvals (AGENTS.md: no general admin bypass).
  if auth.uid() = v_owner_user_id then
    raise exception 'STAFF_SERVICE_SELF_APPROVAL_DENIED' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.staff_service_role_assignments a
    where a.user_id = auth.uid()
      and a.role = v_step.required_role
      and a.active
      and a.valid_from <= current_date
      and (a.valid_until is null or a.valid_until >= current_date)
      and (a.department_id is null or a.department_id = v_request.department_id)
  ) then
    raise exception 'STAFF_SERVICE_APPROVER_SCOPE_DENIED' using errcode = '42501';
  end if;

  update public.staff_service_approval_steps
  set status = p_decision,
      decided_by = auth.uid(),
      decision_reason = nullif(btrim(p_reason), ''),
      decided_at = clock_timestamp()
  where id = v_step.id;

  if p_decision = 'rejected' then
    v_target_status := 'rejected';
    update public.staff_service_requests
    set status = 'rejected',
        decision_reason = btrim(p_reason),
        decided_at = clock_timestamp()
    where id = p_request_id
    returning * into v_request;
  else
    select min(step_order) into v_next_step
    from public.staff_service_approval_steps
    where request_id = p_request_id
      and step_order > v_request.current_step
      and status = 'pending';

    if v_next_step is null then
      v_target_status := 'approved';
      update public.staff_service_requests
      set status = 'approved',
          decision_reason = nullif(btrim(p_reason), ''),
          decided_at = clock_timestamp()
      where id = p_request_id
      returning * into v_request;
    else
      v_target_status := 'in_review';
      update public.staff_service_requests
      set status = 'in_review',
          current_step = v_next_step
      where id = p_request_id
      returning * into v_request;
    end if;
  end if;

  insert into public.staff_service_events (
    request_id,
    event_type,
    actor_user_id,
    actor_role,
    from_status,
    to_status,
    reason,
    metadata,
    correlation_id
  ) values (
    p_request_id,
    'approval_decided',
    auth.uid(),
    v_actor_role,
    v_step.status,
    p_decision,
    nullif(btrim(p_reason), ''),
    jsonb_build_object(
      'step_order', v_step.step_order,
      'request_status', v_target_status
    ),
    p_idempotency_key
  );

  insert into public.staff_service_notifications_outbox (
    recipient_user_id,
    request_id,
    channel,
    template_key,
    payload,
    idempotency_key
  ) values (
    v_owner_user_id,
    p_request_id,
    'in_app',
    case when p_decision = 'approved'
      then 'staff_request_step_approved'
      else 'staff_request_rejected'
    end,
    jsonb_build_object(
      'request_no', v_request.request_no,
      'request_status', v_request.status,
      'reason', nullif(btrim(p_reason), '')
    ),
    p_idempotency_key
  );

  return v_request;
end;
$$;

-- 3) graduate_affairs_list_assignable_staff selected sp.full_name, a column
--    staff_profiles does not have (only full_name_ar / full_name_en), so the
--    assignee list in the graduates-affairs workspace never loaded.

create or replace function public.graduate_affairs_list_assignable_staff()
returns table(user_id uuid, full_name text, role_code text)
language plpgsql stable security definer set search_path to 'public','pg_temp' as $$
begin
  if auth.uid() is null then raise exception 'GRADUATE_AFFAIRS_NOT_AUTHENTICATED'; end if;
  if not public.ga_can_read_operational_catalog() then raise exception 'GRADUATE_AFFAIRS_ACCESS_DENIED'; end if;
  return query
  select distinct sp.user_id,
         coalesce(nullif(btrim(sp.full_name_ar), ''), 'موظف شؤون الخريجين') as full_name,
         r.code as role_code
  from public.request_processing_assignments a
  join public.request_processing_units u on u.id = a.unit_id and u.code = 'graduate_affairs' and u.is_active
  join public.request_processing_roles r on r.id = a.role_id and r.is_active
   and r.code in ('graduate_affairs_manager', 'graduate_affairs_specialist')
  join public.staff_profiles sp on sp.status = 'active'
   and ((a.assignment_type = 'staff_profile' and sp.id = a.staff_profile_id)
     or (a.assignment_type = 'user' and sp.user_id = a.user_id))
  where a.is_active
    and (a.starts_at is null or a.starts_at <= now())
    and (a.ends_at is null or a.ends_at > now())
    and sp.user_id is not null
  order by 2;
end $$;

-- 4) A deactivated staff/faculty profile kept its processing bindings
--    (no status check), so the person could still act on student request
--    steps through still-valid sessions.

CREATE OR REPLACE FUNCTION public.current_user_has_exact_processing_binding(
  p_unit_id uuid, p_role_id uuid
)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
  SELECT auth.uid() IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.request_processing_assignments rpa
    WHERE rpa.is_active = true
      AND (rpa.starts_at IS NULL OR rpa.starts_at <= now())
      AND (rpa.ends_at IS NULL OR rpa.ends_at > now())
      AND rpa.unit_id = p_unit_id AND rpa.role_id = p_role_id
      AND (
        (rpa.assignment_type = 'user' AND rpa.user_id = auth.uid())
        OR (rpa.assignment_type = 'staff_profile' AND EXISTS (
          SELECT 1 FROM public.staff_profiles sp
          WHERE sp.id = rpa.staff_profile_id AND sp.user_id = auth.uid()
            AND COALESCE(lower(sp.status), 'active') NOT IN ('inactive','suspended','disabled')))
        OR (rpa.assignment_type = 'faculty_profile' AND EXISTS (
          SELECT 1 FROM public.faculty_profiles fp
          WHERE fp.id = rpa.faculty_profile_id AND fp.user_id = auth.uid()
            AND COALESCE(lower(fp.status), 'active') NOT IN ('inactive','suspended','disabled')))
        OR (rpa.assignment_type = 'position_assignment' AND EXISTS (
          SELECT 1 FROM public.position_assignments pa
          WHERE pa.id = rpa.position_assignment_id AND pa.user_id = auth.uid()
            AND pa.is_active = true
            AND (pa.assigned_to IS NULL OR pa.assigned_to >= CURRENT_DATE)))
      )
  );
$function$;

COMMIT;
