/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PortalLoginRouteImport } from './routes/portal-login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentChangePasswordRouteImport } from './routes/student.change-password'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as DepartmentsCodeRouteImport } from './routes/departments.$code'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminResearchRouteImport } from './routes/admin/research'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminFacultyRouteImport } from './routes/admin/faculty'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal-login',
  path: '/portal-login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentChangePasswordRoute = StudentChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => StudentRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const DepartmentsCodeRoute = DepartmentsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => DepartmentsRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResearchRoute = AdminResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/news': typeof NewsRouteWithChildren
  '/portal-login': typeof PortalLoginRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/departments/$code': typeof DepartmentsCodeRoute
  '/news/$slug': typeof NewsSlugRoute
  '/student/change-password': typeof StudentChangePasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/news': typeof NewsRouteWithChildren
  '/portal-login': typeof PortalLoginRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/departments/$code': typeof DepartmentsCodeRoute
  '/news/$slug': typeof NewsSlugRoute
  '/student/change-password': typeof StudentChangePasswordRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/news': typeof NewsRouteWithChildren
  '/portal-login': typeof PortalLoginRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/departments/$code': typeof DepartmentsCodeRoute
  '/news/$slug': typeof NewsSlugRoute
  '/student/change-password': typeof StudentChangePasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/departments'
    | '/events'
    | '/faculty'
    | '/news'
    | '/portal-login'
    | '/research'
    | '/sitemap.xml'
    | '/student'
    | '/admin/contacts'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/research'
    | '/admin/settings'
    | '/departments/$code'
    | '/news/$slug'
    | '/student/change-password'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/events'
    | '/faculty'
    | '/news'
    | '/portal-login'
    | '/research'
    | '/sitemap.xml'
    | '/admin/contacts'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/research'
    | '/admin/settings'
    | '/departments/$code'
    | '/news/$slug'
    | '/student/change-password'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/departments'
    | '/events'
    | '/faculty'
    | '/news'
    | '/portal-login'
    | '/research'
    | '/sitemap.xml'
    | '/student'
    | '/admin/contacts'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/research'
    | '/admin/settings'
    | '/departments/$code'
    | '/news/$slug'
    | '/student/change-password'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  NewsRoute: typeof NewsRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
  ResearchRoute: typeof ResearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-login': {
      id: '/portal-login'
      path: '/portal-login'
      fullPath: '/portal-login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/change-password': {
      id: '/student/change-password'
      path: '/change-password'
      fullPath: '/student/change-password'
      preLoaderRoute: typeof StudentChangePasswordRouteImport
      parentRoute: typeof StudentRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/departments/$code': {
      id: '/departments/$code'
      path: '/$code'
      fullPath: '/departments/$code'
      preLoaderRoute: typeof DepartmentsCodeRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/research': {
      id: '/admin/research'
      path: '/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AdminResearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminResearchRoute: typeof AdminResearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactsRoute: AdminContactsRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminResearchRoute: AdminResearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DepartmentsRouteChildren {
  DepartmentsCodeRoute: typeof DepartmentsCodeRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsCodeRoute: DepartmentsCodeRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface StudentRouteChildren {
  StudentChangePasswordRoute: typeof StudentChangePasswordRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentChangePasswordRoute: StudentChangePasswordRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  NewsRoute: NewsRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
