// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import {
  assertPortalRuntimeHost,
  assertPortalSupabasePublishableKey,
  assertPortalSupabaseUrl,
  portalFallbackSupabasePublishableKey,
  portalFallbackSupabaseUrl,
  resolvePortalDeployTarget,
} from "./deployment-profile";

function createSupabaseClient() {
  const DEPLOY_TARGET = resolvePortalDeployTarget(
    import.meta.env.VITE_PORTAL_DEPLOY_TARGET,
    process.env.PORTAL_DEPLOY_TARGET,
  );
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    portalFallbackSupabaseUrl(DEPLOY_TARGET);
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    portalFallbackSupabasePublishableKey(DEPLOY_TARGET);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  assertPortalRuntimeHost(DEPLOY_TARGET);
  const SAFE_URL = assertPortalSupabaseUrl(DEPLOY_TARGET, SUPABASE_URL);
  const SAFE_PUBLISHABLE_KEY = assertPortalSupabasePublishableKey(
    DEPLOY_TARGET,
    SUPABASE_PUBLISHABLE_KEY,
  );

  return createClient<Database>(SAFE_URL, SAFE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop) {
    if (!_supabase) _supabase = createSupabaseClient();
    const value = Reflect.get(_supabase, prop, _supabase);

    // SupabaseClient methods access internal fields such as `rest` through
    // `this`. Keep that receiver intact even when a service layer stores a
    // method reference (for example `const rpc = supabase.rpc`).
    return typeof value === "function" ? value.bind(_supabase) : value;
  },
});
